### PR TITLE
updates envs

### LINKED ISSUE #941: Daily ExampleData tests failing
### Describe the issue

Daily ExampleData tests failing have failed 3 days in a row for the same reasons.

https://github.com/NeurodataWithoutBorders/nwb-guide/actions/runs/11613365359/job/32347559180
macos-latest: `ModuleNotFoundError: No module named 'ndx_pose'`
macos-13: `ModuleNotFoundError: No module named 'tables'`
windows-latest: `ModuleNotFoundError: No module named 'tables'`

### Steps to Reproduce

See GitHub actions logs

### Operating System

Mac, Windows

### GUIDE Version

main

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

### PR DESCRIPTION
**Pull request by luiztauffer**
- [x] Fix #941
- [x] updates DLC example dataset from GIN

### CODE REVIEW

**Comment by luiztauffer** [comment]
@bendichter @rly this fixes the import errors happening on tests. It also fixes an error due to a test DLC data that has been removed from GIN

**Comment by bendichter** [comment]
LGTM!

**Review by rly — APPROVED** [review]
Looks good to me. Thanks!

**Comment by rly** [comment]
PR tests and daily tests pass on this branch. Looks great. Thank you @luiztauffer !

**Pull request merged**
