### PR TITLE
Create frontend and backend for handling session iteration + metadata extraction

### PR DESCRIPTION
**Pull request by garrettmflynn**
This PR begins to address #78 by creating a frontend page and backend endpoint to handle automatic subject and session source data + metadata detection. It was tested on SpikeGLX data from the `cloud-and-guide-testing-data` S3 bucket.

When testing this PR, make sure to use the latest version of [Feature Branch 377](https://github.com/catalystneuro/neuroconv/pull/377), which allows for using an fstring to detect subjects and sessions.

Note that the current implementation of autodetection funnels the returned results into **one subject and session** to avoid issues with rendering further down the GUIDE workflow, allowing us to separate UI improvements into a separate PR.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
It keeps refusing the connection to the backend for me - any ideas why that might be?

**Comment by garrettmflynn** [comment]
I reinstalled the Python dependencies, including the local neuroconv link, and it worked fine. 

If you want more informative errors, you can run **npm run dev:server** to see what's going on with the server without Flask's error handling.

**Comment by garrettmflynn** [comment]
Sorry actually **python pyflask/app.py 3000**, which will circumvent the Flask manager

**Comment by CodyCBakerPhD** [comment]
> I reinstalled the Python dependencies, including the local neuroconv link, and it worked fine.

Yes, I figured it out lol, guess you saw before I deleted

**Comment by garrettmflynn** [comment]
Finished implementing a session manager, which lists all sessions (with the subject prepended) and allows users to toggle between information specifically for that session.

Can make subject groupings a dropdown for more cohesion and less clutter when scaling up—but right now rendering as a path-based system is sufficient for small datasets.

Some additional improvements in the pipeline include:
1. Allow for triggering a preview for any session on the Metadata page
2. Indicate whether all requirements are satisfied by the manager
3. Notify about sessions that are not validated before throwing individual messages about each session (only when one session is left invalidated) 
  - We could also allow for validating per-session similar / in addition to the preview rendering (i.e. a single Validate and Preview button)

**Comment by garrettmflynn** [comment]
@CodyCBakerPhD This should be good to go. I've implemented all the latest requirements noted in #78, as well as noted the trade-offs of those implementations there.

**Comment by garrettmflynn** [comment]
@CodyCBakerPhD Should be good! Will finish this PR up before submitting one on a subjects page / table.

**Comment by CodyCBakerPhD** [comment]
When trying this out now on current NC main, I get the following errors in the console when I try to continue after specifying my iteration pattern

```javascript
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'remove')
    at ae.<anonymous> (index.js:60720:21)
index.js:39540
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'npI1')
    at GuidedPathExpansionPage.merge (index.js:39540:58)
    at GuidedFooter.onNext [as __onNext] 
```

Is it working for you?

**Comment by garrettmflynn** [comment]
Not on a new project. Thanks for catching this!

Just pushed the fix, didn't end up creating a field in the global metadata before trying to merge.

**Comment by CodyCBakerPhD** [comment]
New error now:

```javascript
index.js:60722 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'remove')
    at ae.<anonymous> (index.js:60722:21)
(anonymous) @ index.js:60722
await in (anonymous) (async)
onChange @ index.js:60614
(anonymous) @ index.js:60125
(anonymous) @ index.js:60823
(anonymous) @ index.js:60823
updated @ index.js:60845
_$AE @ index.js:250
performUpdate @ index.js:241
scheduleUpdate @ index.js:224
_$Ej @ index.js:220
await in _$Ej (async)
requestUpdate @ index.js:211
u @ index.js:154
d$1 @ index.js:95
s @ index.js:545
ae @ index.js:60541
(anonymous) @ index.js:61906
(anonymous) @ index.js:39565
(anonymous) @ index.js:39565
mapSessions @ index.js:39565
render @ index.js:61926
update @ index.js:553
performUpdate @ index.js:237
scheduleUpdate @ index.js:224
_$Ej @ index.js:220
await in _$Ej (async)
requestUpdate @ index.js:211
(anonymous) @ index.js:39517
setMain @ index.js:62687
Dashboard.window.onpushstate.window.onpopstate @ index.js:62636
Dashboard.window.history.pushState @ index.js:62634
save @ index.js:39450
(anonymous) @ index.js:39533
onNext @ index.js:61872
handleEvent @ index.js:511
3index.js:60722 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'remove')
    at ae.<anonymous> (index.js:60722:21)
(anonymous) @ index.js:60722
await in (anonymous) (async)
onChange @ index.js:60614
(anonymous) @ index.js:60125
(anonymous) @ index.js:60823
(anonymous) @ index.js:60823
updated @ index.js:60845
_$AE @ index.js:250
performUpdate @ index.js:241
scheduleUpdate @ index.js:224
_$Ej @ index.js:220
await in _$Ej (async)
requestUpdate @ index.js:211
u @ index.js:154
d$1 @ index.js:95
s @ index.js:545
ae @ index.js:60541
(anonymous) @ index.js:61906
(anonymous) @ index.js:39565
(anonymous) @ index.js:39565
mapSessions @ index.js:39565
render @ index.js:61926
update @ index.js:553
performUpdate @ index.js:237
scheduleUpdate @ index.js:224
_$Ej @ index.js:220
await in _$Ej (async)
requestUpdate @ index.js:211
(anonymous) @ index.js:39517
setMain @ index.js:62687
Dashboard.window.onpushstate.window.onpopstate @ index.js:62636
Dashboard.window.history.pushState @ index.js:62634
save @ index.js:39450
(anonymous) @ index.js:39533
onNext @ index.js:61886
await in onNext (async)
handleEvent @ index.js:511
index.js:61887          POST http://127.0.0.1:4242/neuroconv/metadata 500 (INTERNAL SERVER ERROR)
(anonymous) @ index.js:61887
(anonymous) @ index.js:39565
(anonymous) @ index.js:39565
mapSessions @ index.js:39565
onNext @ index.js:61886
await in onNext (async)
handleEvent @ index.js:511
index.js:61887          POST http://127.0.0.1:4242/neuroconv/metadata 500 (INTERNAL SERVER ERROR)
(anonymous) @ index.js:61887
(anonymous) @ index.js:39565
(anonymous) @ index.js:39565
mapSessions @ index.js:39565
onNext @ index.js:61886
await in onNext (async)
handleEvent @ index.js:511
index.js:61897 Uncaught (in promise) Error: Failed to get metadata for source data provided: Size of available data is not a multiple of the data-type size.
    at index.js:61897:44
    at async Promise.all (/D:/GitHub/nwb-guide/index 2)
    at async GuidedFooter.onNext [as __onNext] (index.js:61886:26)
```

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
