### PR TITLE
End-to-End Tests + Screenshot capability

### PR DESCRIPTION
**Pull request by garrettmflynn**
This PR will use the data generated from #530 to run end-to-end tests using Puppeteer and automatically produce screenshots for a new tutorial on the GUIDE.

### CODE REVIEW

**Comment by garrettmflynn** [comment]
@CodyCBakerPhD Full end-to-end test is completed, including DANDI upload! Just have to tweak a few of the test timeout values so this works across all CI platforms.

**Comment by garrettmflynn** [comment]
Looks like it works! Let's write up some suggested improvements for these screenshots?

**Comment by CodyCBakerPhD** [comment]
>  including DANDI upload!

Just checking really quick - that's to staging, right?

**Comment by CodyCBakerPhD** [comment]
> Let's collect some suggested improvements for these screenshots here then?

I would say having e2e tests at all is a fantastic thing to have; fine running of screenshots can always fall into a follow-up that specifically writes the tutorial

BTW, where are the screenshots found?

**Comment by garrettmflynn** [comment]
> Just checking really quick - that's to staging, right?

Yep! It's to a hardcoded Dandiset that I made on staging. I've started passing my API key as a Action secret to support this behavior.

**Comment by garrettmflynn** [comment]
> I would say having e2e tests at all is a fantastic thing to have; fine tuning of screenshots can always fall into a follow-up that specifically writes the tutorial

Sounds good!

> BTW, where are the screenshots found?

Screenshots are in `tests/screenshots` at the moment.

**Comment by CodyCBakerPhD** [comment]
> Do you want these to show up in the public repo?

I say let's decide that in the follow-up focusing on the tutorial specifically; will have to think about upsides/downsides

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by CodyCBakerPhD** [comment]
Ahh, bummer: chromatic failing here https://github.com/NeurodataWithoutBorders/nwb-guide/actions/runs/7875721966

**Pull request merged**
