### PR TITLE
Pre-Form Basic Implementation

### PR DESCRIPTION
**Pull request by garrettmflynn**
This PR is a first pass at the pre-form page discussed in #554, with relevant interactions across the GUIDE workflow.

This will help constrain the tutorial workflow so users are only presented with the UI they will actually use for a given section.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
Instead of checkboxes, can they be yes/no radio selectors? More personable since we're asking questions (again, TurboTax-like)

**Comment by CodyCBakerPhD** [comment]
Other than that, it sure feels really good to not even have to see the locate data page if I say no

Also nice that is shows up grayed out in the main progress tab so I know it 'would' have been there otherwise

**Comment by garrettmflynn** [comment]
> Instead of checkboxes, can they be yes/no radio selectors? More personable since we're asking questions (again, TurboTax-like)

This will be applied globally with https://github.com/NeurodataWithoutBorders/nwb-guide/pull/640

**Comment by garrettmflynn** [comment]
Whoops I forgot to update the tests after skipping the Subjects page. 

This should be ready to review now.

**Pull request merged**
