### PR TITLE
Defer validation to form change

### LINKED ISSUE #750: [Enhancement]: Don't make Project Setup > Name red to start
### What would you like to see added to the NWB GUIDE?

image

When you first enter the Project Setup page, you see red, which suggests an error. While the lack of name is technically invalid, the red is a little jarring. This is also not typical in web forms. The error typically appears only after trying to submit the form without filling out the required fields.

On the next page:
image

The Subject ID and Session ID are required but do not start red until you click Next without filling them out. I think that is more visually appealing and more consistent with other UIs.

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

Yes

### Did you confirm this feature was not already reported?

Yes

### PR DESCRIPTION
**Pull request by garrettmflynn**
fix #750

### CODE REVIEW

**Comment by rly** [comment]
I can't seem to launch the app from dev. Any ideas?

image

```
dev server running for the electron renderer process at:

  ➜  Local:   http://127.0.0.1:5173/
  ➜  Network: use --host to expose

start electron app...

2024-04-16 16:22:54.021 Electron[58466:1244591] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
Killing all previous processes
Traceback (most recent call last):
  File "/Users/rly/Documents/NWB/nwb-guide/pyflask/app.py", line 20, in <module>

    from flask import Flask, request, send_from_directory, send_file
ModuleNotFoundError: No module named 'flask'

(node:58466) UnhandledPromiseRejectionWarning: undefined
(Use `Electron --trace-warnings ...` to show where the warning was created)
(node:58466) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by rly** [comment]
Oh! My bad. Wrong conda environment! -.-

**Comment by rly** [comment]
Screenshot 2024-04-16 at 4 27 23 PM

The red error message popup disappears after about 18 seconds. That feels long. The error message popup on the subject ID / session ID page disappears after about 6 seconds. That feels better. Can we change it from 18 to 6? 

Even better, could we make the popup disappear after the error has been resolved in the immediate form validation? That is minor and should probably be a separate PR

**Comment by garrettmflynn** [comment]
Updated both. Thanks for suggesting this!

**Comment by rly** [comment]
Beautiful! Thank you.

**Review by rly — APPROVED** [review]

**Pull request merged**
