### PR TITLE
Remove unused commands from package.json

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
I don't think we use either of these in practice

### CODE REVIEW

**Review by garrettmflynn — CHANGES_REQUESTED** [review]
postinstall is actually a standard command that's triggered after installation. Interestingly enough, I just learned that you can append "pre" or "post" to any of the keys underneath the "script" field to trigger before/after the main script runs. 

The format command is fine to remove though.

**Comment by CodyCBakerPhD** [comment]
> postinstall is actually a standard command that's triggered after installation.

So it must be included in the `package.json` in order to allow installation? Even though it's never called explicitly by us? Is that an `electron-vite` thing or just an `npm` thing?

**Comment by CodyCBakerPhD** [comment]
Oh, I see

https://docs.npmjs.com/cli/v9/using-npm/scripts#pre--post-scripts

**Review by garrettmflynn — APPROVED** [review]
Looks good to me!

**Pull request merged**
