### PR TITLE
Add single-plane Bruker Interface

### PR DESCRIPTION
**Pull request by garrettmflynn**
This is a useful test for #393 and the first ophys interface we can test.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
Oh, was the discussion/changes of the JSON handling only relevant for rendering of the metadata forms for ophys?

If so I really think we should add metadata control for ophys in a standalone PR and leave these interface introductions to be standalone additions with their own debugs since there's a lot we would want to change about the metadata forms independent of each format

**Comment by CodyCBakerPhD** [comment]
Even with the changes, I was unable to proceed past the metadata page

```javascript
Uncaught (in promise) Error: Request to convert failed: None is not of type 'number'

Failed validating 'type' in schema['properties']['Ophys']['properties']['ImagingPlane']['items']['properties']['excitation_lambda']:
    {'description': 'Excitation wavelength in nm.', 'type': 'number'}

On instance['Ophys']['ImagingPlane'][0]['excitation_lambda']:
    None
    at run (utils.js:37:33)
    at async GuidedMetadataPage.runConversions (Page.js:167:28)
    at async GuidedFooter.onNext [as __onNext] (GuidedMetadata.js:43:27)
```

So I say let's save the metadata exposure for a follow-up and just use the internally generated default values inside the API functions for now, which means we probably don't need to merge #374 or use it as the base here

**Comment by garrettmflynn** [comment]
Ah, I see what's going on. Since I'm passing the object back to the Flask server. using `JSON.stringify`, those NaN values are being converted to `null` (`None` in Python).

Your suggestion makes sense. It's similar to how we're not handling Ecephys metadata at this point as well.

**Comment by garrettmflynn** [comment]
Alright I was able to run a conversion using the changes made in #393, essentially implementing what you were thinking might be useful in Neuroconv itself (as a layer above PyNWB / NWB Schema).

**Comment by garrettmflynn** [comment]
Thought I did switch the base. Does it look different on your end?

**Comment by CodyCBakerPhD** [comment]
> Thought I did switch the base. Does it look different on your end?

The base is as you indicate, but I wasn't sure if I should hit the 'update branch' button given this branch also started from a different base originally

**Comment by garrettmflynn** [comment]
Oh sure. I'd done that manually to—but wouldn't hurt to confirm

**Comment by CodyCBakerPhD** [comment]
When launching the app to test this, saw https://github.com/NeurodataWithoutBorders/nwb-guide/issues/311#issuecomment-1735995141

Though I suspect it may be residual from another PR such as #392 

Not originally detected because I used hot reloading on an already launched app; this only shows when I closed by testing #392 and reopened after switching the branch

**Comment by CodyCBakerPhD** [comment]
This actually does propagate to an issue where the backend does not connect anymore

```javascript
TypeError: paths.subfolders.stubs is not iterable (cannot read property undefined)
    at Object.<anonymous> (D:\GitHub\nwb-guide\build\main\main.js:15954:37)
    at Module.<anonymous> (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13377)
    at loadApplicationPackage (D:\GitHub\nwb-guide\node_modules\electron\dist\resources\default_app.asar\main.js:121:16)
    at Object.<anonymous> (D:\GitHub\nwb-guide\node_modules\electron\dist\resources\default_app.asar\main.js:233:9)
    at Module.<anonymous> (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
Killing all previous processes
```

**Comment by CodyCBakerPhD** [comment]
Which is also an issue on `main` and so blocking testing of everything else

Would you like me to raise an issue for it?

**Comment by garrettmflynn** [comment]
Just forced a push to `main`. It was from #377, I remember making the correct change, but must not have saved properly before pushing.

**Comment by CodyCBakerPhD** [comment]
OK working well now

Just leaving as a note, the dual-channel example (NCCR62_2023_07_06_IntoTheVoid_t_series_Dual_color-000) fails unless you know the stream name for each optic channel, but that's hard to tell ATM

Main solution will be to expose the 'simple' mode of interface selection, which is actually to use the subconverters that handle this automatically

**Comment by CodyCBakerPhD** [comment]
Can you add a source data story so we can keep track of how the stream name and other future options look?

**Comment by garrettmflynn** [comment]
We may want to add a trigger to regenerate the Source Data stories whenever the guidedGlobalMetadata file changes, since all I have to do is manually run `python generateInterfaceSchema.py`. I thought of this since we missed doing this with Spike2 before.

What do you think?

**Comment by CodyCBakerPhD** [comment]
> We may want to add a trigger to regenerate the Source Data stories whenever the guidedGlobalMetadata file changes, since all I have to do is manually run python generateInterfaceSchema.py. I thought of this since we missed doing this with Spike2 before.

It would be nice if not too much trouble - what kind of trigger were you thinking of?

Various CI around the ecosystem have a step called `assess-file-changes` and other dependent jobs after that to send logic back to the display to notify a specific file was changed as a reminder; auto running the generator, commiting, and pushing back to the repo is also possible but much more of a headache to setup

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by garrettmflynn** [comment]
Yeah just that. Detect changes to that file, run the generation script if so, then push back to the repo.

If it's a hassle, there's no real need though. Manual is fine—we just have to remember to re-sync every so often.

**Comment by CodyCBakerPhD** [comment]
> If it's a hassle, there's no real need though. Manual is fine—we just have to remember to re-sync every so often.

Pushing back would be a hassle

Setting up a reminder based on file changes is pretty easy, I can show you how to set it up tomorrow

**Pull request merged**
