### PR TITLE
Fix Windows Script Path

### PR DESCRIPTION
**Pull request by garrettmflynn**
This PR is an attempt to fix how the distribution Flask server is targeted on Windows builds.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
Trying now

**Comment by CodyCBakerPhD** [comment]
Just for added context, this again

image

**Comment by CodyCBakerPhD** [comment]
But launches fine immediately after that, here's the dev console

```javascript
index-6be853e2.js:48423 [main-process]: Packaged Script Path D:\NWB GUIDE\resources\app\build\flask\flask\nwb-guide.exe
(anonymous) @ index-6be853e2.js:48423
index-6be853e2.js:48423 [main-process]: Resolved Script Path D:\NWB GUIDE\resources\app\pyflask\app.py
```

**Comment by garrettmflynn** [comment]
What's the actual path to the build `.exe`?

**Comment by CodyCBakerPhD** [comment]
That's what I was just looking up: `D:\NWB GUIDE\resources\app\build\flask\nwb-guide`

So it's the double-flask that's causing it by the looks of it

**Comment by garrettmflynn** [comment]
Ah sure. Just need to remove `PYFLASK_BUILD_SUBFOLDER_NAME` from the path declaration

**Comment by garrettmflynn** [comment]
@CodyCBakerPhD Alright can you try again?

**Comment by CodyCBakerPhD** [comment]
Negatory

image

**Comment by garrettmflynn** [comment]
Hmmm. Assuming you got the ENOENT error still?

**Comment by garrettmflynn** [comment]
```
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are missing from the target environment:
  - mkl
  - mkl-service
```

**Comment by CodyCBakerPhD** [comment]
> Hmmm. Assuming you got the ENOENT error still?

Always 😆

**Comment by garrettmflynn** [comment]
@CodyCBakerPhD This works now!

**Comment by CodyCBakerPhD** [comment]
Confirmed!

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
