### PR TITLE
Add legend to guided mode

### LINKED ISSUE #635: [Feature]: NWB inspector results unclear
### What would you like to see added to the NWB GUIDE?

image

It would not be clear to a user that these are best practice suggestions that can be safely ignored. Could we find some way to indicate their importance? The color is nice but that does not tell us we can ignore them.

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

Yes

### Did you confirm this feature was not already reported?

Yes

### PR DESCRIPTION
**Pull request by garrettmflynn**
fix #635

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn Haven't checked if it's this branch or not, but standalone validation page has the 'cannot render because of misformatted schema' thing

**Comment by garrettmflynn** [comment]
Yep noticed this as well. Will update in a separate PR

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn Many conflicts now

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn Any idea what happened here? Did you rebase this from a really old commit? There are a huge number of breaking changes reverting PRs over the last week (including environment configuration, the doc button, even schema reversions)

**Comment by garrettmflynn** [comment]
Hmmm I have no idea. Things are being reverted? 

I was fiddling with this as soon as Ben submitted the issue, so it wouldn't go any further than that.

**Comment by CodyCBakerPhD** [comment]
In that case it might be easier to reimplement this on a fresh branch

**Comment by garrettmflynn** [comment]
Wow! It's insane how bad this PR's file changes are. 

Replaced by https://github.com/NeurodataWithoutBorders/nwb-guide/pull/671

**Pull request closed without merging**
