### PR TITLE
Add legend to Guided Mode

### PR DESCRIPTION
**Pull request by garrettmflynn**
fix https://github.com/NeurodataWithoutBorders/nwb-guide/issues/635

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
Should we include this on the standalone page as well?

**Comment by garrettmflynn** [comment]
We can. I'd just have to reimplement the changes there.

Wanted to confirm the general structure first.

**Comment by CodyCBakerPhD** [comment]
Overall I think it looks great; it might be a _little_ tall on a _very_ small screen but since you have the smallest of all, I'll let you be the judge on that. On a big screen looks great

**Comment by garrettmflynn** [comment]
Updated the style and added to the standalone page
Screenshot 2024-03-14 at 10 56 47 AM

Screenshot 2024-03-14 at 10 57 34 AM

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
