### PR TITLE
Fix PyInstaller Spec preparation for other formatting

### LINKED ISSUE #378: Flask Build Fails on Mac (Intel)
An error is thrown from the Flask server when created and run on a Mac (Intel). Although the GUIDE will open, the server will fail during the `startup/preload-imports` API call:
```
[main-process]: INTEL MKL ERROR: dlopen(/Applications/NWB GUIDE.app/Contents/Resources/flask/libmkl_core.1.dylib, 0x0009): tried: '/Applications/NWB GUIDE.app/Contents/Resources/flask/libmkl_core.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/NWB GUIDE.app/Contents/Resources/flask/libmkl_core.1.dylib' (no such file), '/Applications/NWB GUIDE.app/Contents/Resources/flask/libmkl_core.1.dylib' (no such file).
Intel MKL FATAL ERROR: Cannot load libmkl_core.1.dylib.
```

Rebuilding the spec results in an invalid file: 

```python
# -*- mode: python ; coding: utf-8 -*-
import sys
from pathlib import Path

sys.setrecursionlimit(sys.getrecursionlimit() * 5)

from PyInstaller.utils.hooks import collect_data_files
from PyInstaller.utils.hooks import collect_all

datas = [('./paths.config.json', '.'), ('./package.json', '.')]
binaries = []
hiddenimports = ['scipy._distributor_init', 'scipy._lib.messagestream', 'scipy._lib._ccallback', 'scipy._lib._testutils', 'email_validator']
datas += collect_data_files('jsonschema_specifications')
tmp_ret = collect_all('nwbinspector')
datas += tmp_ret[0]; binaries += tmp_ret[1]; hiddenimports += tmp_ret[2]
tmp_ret = collect_all('neuroconv')
datas += tmp_ret[0]; binaries += tmp_ret[1]; hiddenimports += tmp_ret[2]
tmp_ret = collect_all('pynwb')
datas += tmp_ret[0]; binaries += tmp_ret[1]; hiddenimports += tmp_ret[2]
tmp_ret = collect_all('hdmf')
datas += tmp_ret[0]; binaries += tmp_ret[1]; hiddenimports += tmp_ret[2]
tmp_ret = collect_all('ndx_dandi_icephys')
datas += tmp_ret[0]; binaries += tmp_ret[1]; hiddenimports += tmp_ret[2]
tmp_ret = collect_all('ci_info')
datas += tmp_ret[0]; binaries += tmp_ret[1]; hiddenimports += tmp_ret[2]


block_cipher = None


    [f"{Path('pyflask') / 'app.py'}"],
             pathex=[],
             binaries=binaries,
             datas=datas,
             hiddenimports=hiddenimports,
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts, 
          [],
          exclude_binaries=True,
          name='nwb-guide',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas, 
               strip=False,
               upx=True,
               upx_exclude=[],
               name='nwb-guide')
```

**Operating system used:**

- OS: MacOS 13.4.1

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
@garrettmflynn Can you give this a try?

### CODE REVIEW

**Comment by garrettmflynn** [comment]
This outputs a correct specification! Although it seems like the server still fails on the `preload-imports` call.

**Comment by CodyCBakerPhD** [comment]
> Although it seems like the server still fails on the preload-imports call.

Same error as before?

**Comment by garrettmflynn** [comment]
Yep the same one

**Comment by garrettmflynn** [comment]
```
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are missing from the target environment:
  - mkl
  - mkl-service
```

**Comment by garrettmflynn** [comment]
Hmmmm the same error happens when using the CLI without the spec specified now: 

```python
# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files
from PyInstaller.utils.hooks import collect_all

datas = [('./paths.config.json', '.'), ('./package.json', '.')]
binaries = []
hiddenimports = ['scipy._distributor_init', 'scipy._lib.messagestream', 'scipy._lib._ccallback', 'scipy._lib._testutils', 'email_validator']
datas += collect_data_files('jsonschema_specifications')
tmp_ret = collect_all('nwbinspector')
datas += tmp_ret[0]; binaries += tmp_ret[1]; hiddenimports += tmp_ret[2]
tmp_ret = collect_all('neuroconv')
datas += tmp_ret[0]; binaries += tmp_ret[1]; hiddenimports += tmp_ret[2]
tmp_ret = collect_all('pynwb')
datas += tmp_ret[0]; binaries += tmp_ret[1]; hiddenimports += tmp_ret[2]
tmp_ret = collect_all('hdmf')
datas += tmp_ret[0]; binaries += tmp_ret[1]; hiddenimports += tmp_ret[2]
tmp_ret = collect_all('ndx_dandi_icephys')
datas += tmp_ret[0]; binaries += tmp_ret[1]; hiddenimports += tmp_ret[2]
tmp_ret = collect_all('ci_info')
datas += tmp_ret[0]; binaries += tmp_ret[1]; hiddenimports += tmp_ret[2]


block_cipher = None


a = Analysis(['pyflask/app.py'],
             pathex=[],
             binaries=binaries,
             datas=datas,
             hiddenimports=hiddenimports,
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts, 
          [],
          exclude_binaries=True,
          name='nwb-guide',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas, 
               strip=False,
               upx=True,
               upx_exclude=[],
               name='nwb-guide')

```

**Comment by CodyCBakerPhD** [comment]
> Hmmmm the same error happens when using the CLI without the spec specified now:

And this is a fresh conda environment? Using update to date base environment? Any idea when you last successfully built the Flask on this device?

**Comment by garrettmflynn** [comment]
Yeah I'd just updated the environment because of a mismatch between `roiextractors` and `neuroconv`. 

As far as I can remember, it was successful before the change to a uniform spec file. I have a successful build of 0.0.4 on Sept. 11th at 7:54am

**Comment by CodyCBakerPhD** [comment]
> As far as I can remember, it was successful before the change to a uniform spec file. 

Right, but now the attempt to build it _not_ using the uniform spec file also throws the same error if I'm understanding correctly?

So we'd need to evaluate what changed in the environment itself since 9/11/23

**Comment by garrettmflynn** [comment]
Yes, you are correct.

Although I will add that I've been somewhat bad at updating my environment, except in the case of app-breaking issues—so bounding our search by that timeline may be misleading. Worth a shot, but it may not be that cut and dry.

**Comment by garrettmflynn** [comment]
After googling the error, it looks like it might just be that MKL is not installed and Numpy uses it: https://stackoverflow.com/questions/55778337/what-is-intel-mkl-fatal-error-cannot-load-libmkl-core-dylib-while-running-pysp

**Comment by CodyCBakerPhD** [comment]
What do you see from

```python
pip show numpy
```

**Comment by garrettmflynn** [comment]
```
Name: numpy
Version: 1.23.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: /opt/anaconda3/envs/env-electron-python/lib/python3.9/site-packages
Requires: 
Required-by: biopython, bqplot, contourpy, elephant, h5py, hdf5storage, hdmf, imageio, ipydatawidgets, ipympl, ipyvolume, matplotlib, MEArec, MEAutility, mkl-fft, mkl-random, neo, neuroconv, numcodecs, numexpr, nwbinspector, nwbwidgets, opencv-python, opencv-python-headless, pandas, probeinterface, pyEDFlib, pyintan, pymatreader, pynwb, pyopenephys, pythreejs, PyWavelets, quantities, scanimage-tiff-reader, scikit-image, scipy, sleap-io, spikeextractors, spikeinterface, tables, tifffile, trimesh, zarr
```

Though I'd attempted `conda update numpy` before this and the following message was thrown: 

```
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda3/envs/nwb-guide

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2023.08.22 |       hecd8cb5_0         124 KB
    importlib_resources-5.2.0  |     pyhd3eb1b0_1          21 KB
    libuv-1.44.2               |       h6c40b1e_0         388 KB
    mkl_fft-1.3.8              |   py39h6c40b1e_0         195 KB
    mkl_random-1.2.4           |   py39ha357a0b_0         271 KB
    typing-extensions-4.7.1    |   py39hecd8cb5_0          10 KB
    typing_extensions-4.7.1    |   py39hecd8cb5_0          56 KB
    zipp-3.11.0                |   py39hecd8cb5_0          20 KB
    ------------------------------------------------------------
                                           Total:         1.1 MB

The following NEW packages will be INSTALLED:

  blas               pkgs/main/osx-64::blas-1.0-mkl
  intel-openmp       pkgs/main/osx-64::intel-openmp-2023.1.0-ha357a0b_43547
  mkl                pkgs/main/osx-64::mkl-2023.1.0-h8e150cf_43559
  mkl-service        pkgs/main/osx-64::mkl-service-2.4.0-py39h6c40b1e_1
  mkl_fft            pkgs/main/osx-64::mkl_fft-1.3.8-py39h6c40b1e_0
  mkl_random         pkgs/main/osx-64::mkl_random-1.2.4-py39ha357a0b_0
  numpy-base         pkgs/main/osx-64::numpy-base-1.25.2-py39ha186be2_0
  tbb                pkgs/main/osx-64::tbb-2021.8.0-ha357a0b_0

The following packages will be REMOVED:

  libblas-3.9.0-18_osx64_openblas
  libcblas-3.9.0-18_osx64_openblas
  libgfortran-5.0.0-13_2_0_h97931a8_1
  libgfortran5-13.2.0-h2873a65_1
  liblapack-3.9.0-18_osx64_openblas
  libopenblas-0.3.24-openmp_h48a4ad5_0
  llvm-openmp-16.0.6-hff08bdf_0

The following packages will be UPDATED:

  ca-certificates    conda-forge::ca-certificates-2023.7.2~ --> pkgs/main::ca-certificates-2023.08.22-hecd8cb5_0
  libffi               conda-forge::libffi-3.4.2-h0d85af4_5 --> pkgs/main::libffi-3.4.4-hecd8cb5_0
  xz                       conda-forge::xz-5.2.6-h775f41a_0 --> pkgs/main::xz-5.4.2-h6c40b1e_0

The following packages will be SUPERSEDED by a higher-priority channel:

  altgraph           conda-forge/noarch::altgraph-0.17.3-p~ --> pkgs/main/osx-64::altgraph-0.17.3-py39hecd8cb5_0
  bzip2                 conda-forge::bzip2-1.0.8-h0d85af4_4 --> pkgs/main::bzip2-1.0.8-h1de35cc_0
  entrypoints        conda-forge/noarch::entrypoints-0.4-p~ --> pkgs/main/osx-64::entrypoints-0.4-py39hecd8cb5_0
  importlib_resourc~ conda-forge::importlib_resources-6.0.~ --> pkgs/main::importlib_resources-5.2.0-pyhd3eb1b0_1
  libuv                conda-forge::libuv-1.44.2-h0dc2134_1 --> pkgs/main::libuv-1.44.2-h6c40b1e_0
  macholib           conda-forge/noarch::macholib-1.16.2-p~ --> pkgs/main/osx-64::macholib-1.16.2-py39hecd8cb5_0
  msgpack-python     conda-forge::msgpack-python-1.0.5-py3~ --> pkgs/main::msgpack-python-1.0.3-py39haf03e11_0
  ncurses               conda-forge::ncurses-6.4-hf0c8a7f_0 --> pkgs/main::ncurses-6.4-hcec6c5f_0
  numpy              conda-forge::numpy-1.26.0-py39h892e69~ --> pkgs/main::numpy-1.25.2-py39h827a554_0
  pyinstaller-hooks~ conda-forge/noarch::pyinstaller-hooks~ --> pkgs/main/osx-64::pyinstaller-hooks-contrib-2022.14-py39hecd8cb5_0
  readline             conda-forge::readline-8.2-h9e318b2_1 --> pkgs/main::readline-8.2-hca72f7f_0
  setuptools         conda-forge/noarch::setuptools-68.2.2~ --> pkgs/main/osx-64::setuptools-68.0.0-py39hecd8cb5_0
  tk                      conda-forge::tk-8.6.12-h5dbffcc_0 --> pkgs/main::tk-8.6.12-h5d9f67b_0
  typing-extensions  conda-forge/noarch::typing-extensions~ --> pkgs/main/osx-64::typing-extensions-4.7.1-py39hecd8cb5_0
  typing_extensions  conda-forge/noarch::typing_extensions~ --> pkgs/main/osx-64::typing_extensions-4.7.1-py39hecd8cb5_0
  tzdata               conda-forge::tzdata-2023c-h71feb2d_0 --> pkgs/main::tzdata-2023c-h04d1e81_0
  wheel              conda-forge/noarch::wheel-0.41.2-pyhd~ --> pkgs/main/osx-64::wheel-0.38.4-py39hecd8cb5_0
  zipp               conda-forge/noarch::zipp-3.16.2-pyhd8~ --> pkgs/main/osx-64::zipp-3.11.0-py39hecd8cb5_0


Proceed ([y]/n)? y
```

**Comment by CodyCBakerPhD** [comment]
> conda update numpy

`pip install numpy` and `conda install numpy` install from different channels and may come with/without all kinds of baggage

So, to verify, the following workflow causes a problem on non-M1 Mac?

```
conda activate base
conda env remove -n nwb-guide
conda env create -f <path to guide>/environments/environment-MAC.yml
conda activate nwb-guide
pyinstaller <all the flags>
```

**Comment by garrettmflynn** [comment]
I'd used `environments/environment-MAC-arm64.yml`. Is that not the correct environment file?

**Comment by CodyCBakerPhD** [comment]
What does this say?

`python -c "import platform; print(platform.machine()); print(platform.processor())"`

**Comment by CodyCBakerPhD** [comment]
I'm 99% sure `environment-MAC-arm64.yml` is  the M1 version, but I'm curious what the specs above say for you

**Comment by garrettmflynn** [comment]
```
x86_64
i386
```

**Comment by CodyCBakerPhD** [comment]
Yep, as expected - can you try the process again but this time use the non-arm64 environment file?

**Comment by garrettmflynn** [comment]
lol yep, my bad for mixing up the two

**Comment by CodyCBakerPhD** [comment]
Not at all - I noticed a while back that the miniconda page specifically clarifies the two

https://docs.conda.io/projects/miniconda/en/latest/

So we should probably add more info to the base mac name to clarify

**Comment by garrettmflynn** [comment]
Hmmm tested several times to check the environment was properly reset—as well as using the CLI instead of the hardcoded spec.

No luck. I keep getting the same error 

```
INTEL MKL ERROR: dlopen(/Users/garrettflynn/Documents/Github/nwb-guide/build/flask/nwb-guide/libmkl_core.1.dylib, 0x0009): tried: '/Users/garrettflynn/Documents/Github/nwb-guide/build/flask/nwb-guide/libmkl_core.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/garrettflynn/Documents/Github/nwb-guide/build/flask/nwb-guide/libmkl_core.1.dylib' (no such file), '/Users/garrettflynn/Documents/Github/nwb-guide/build/flask/nwb-guide/libmkl_core.1.dylib' (no such file).
```

**Comment by CodyCBakerPhD** [comment]
What about forcing install? Such as

```
conda install mkl
```

**Comment by garrettmflynn** [comment]
No luck. Same issue

**Review by garrettmflynn — APPROVED** [review]
Looks good. This fixes the Pyinstaller spec generated for Mac—though we still have the ongoing build issue related to MKL.

**Pull request merged**
