### PR TITLE
Skip dandi upload

### LINKED ISSUE #702: [Feature]: Add page after conversion before upload that says your data has been converted and where
### What would you like to see added to the NWB GUIDE?

A user may not want to upload their converted data immediately to DANDI. Perhaps they are interested only in conversion so that they can run an analysis on the NWB file, or they want to append trials or other custom data through pynwb/matnwb to the NWB file. Currently after conversion, they are prompted to enter DANDI API keys if they haven't entered them yet and then asked to upload the data to DANDI. They do not know where their converted files are unless they explored the Settings.

I think it would be useful to add an informational page after conversion and before upload that says something like:

"Success! Your data has been converted to NWB. You can access the NWB files at [path]. 

If you are ready to upload your NWB files to the DANDI Archive, press **Next**. If not, press **Exit Current Pipeline** to return to the main page. You can always return to this pipeline to upload these NWB files to DANDI."

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

Yes

### Did you confirm this feature was not already reported?

Yes

### PR DESCRIPTION
**Pull request by garrettmflynn**
fix #702

The updated results page if you skip DANDI upload looks like this:
Screenshot 2024-03-25 at 4 56 08 PM

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
Could you also add the folder file navigator button from the other pages to here? I know it says where they are but still convenient to be able to just press a button to get there

Also just a tad odd that this is listed as being _after_ a greyed out DANDI conversion - could it perhaps be before? (but still only show up if pre-form specified to not upload to DANDI. Kind of tells a story that, 'if they had said they wanted to upload' then 'upload would be the last step'

**Comment by garrettmflynn** [comment]
Oh sure. This solution allowed me to avoid adding an additional page.

Assuming it'd be alright if the Conversion review page (before DANDI upload) was greyed out during a DANDI workflow?

If so, I'll update the current Conversion review page (after upload) to Upload review.

**Comment by CodyCBakerPhD** [comment]
Sure

Also, seems like tests are failing

**Comment by garrettmflynn** [comment]
Thanks for flagging. I'll tackle this first thing tomorrow

**Comment by garrettmflynn** [comment]
Gonna render a bit weird on old pipelines since the names and labels were changed. Make sure to test on regenerated test pipelines.

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn Failing tests

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
