### PR TITLE
Testing #895

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
Running #895 tests with CI permissions

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
`npm ci` is stalling out on all mac runners here despite nothing related being changed

Dailies yesterday ran fine, triggered on `main` just now to double check

Might be a live service `npm` issue

**Comment by CodyCBakerPhD** [comment]
Yeah even `main` is struggling ATM

I'll retry this again tomorrow

**Comment by CodyCBakerPhD** [comment]
It's been several days of failure now so seems to be a reliable issue

Trying to debug on this branch

**Comment by CodyCBakerPhD** [comment]
@rly See #901 for formal record, but just to clarify, local builds on my Mac work just fine on this branch, it's only the CI that is problematic as of 5 days ago

So I've disabled those in #900 (merged into this)

**Comment by rly** [comment]
Thanks for the formal record. That is useful. I will experiment with a couple things, but otherwise I think disabling the Mac builds until we have more time or help on how to dig deeper makes sense.

**Review by rly — APPROVED** [review]

**Pull request merged**
