### PR TITLE
Replace HTML representation of the NWB file with Neurosift

### PR DESCRIPTION
**Pull request by garrettmflynn**
This PR uses an iframe to point the Neurosift application to the locally hosted stub file being previewed to provide a comprehensive look at the contents of the file.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
Looks great! Slight delay while it launched but then was A-OK

One question maybe; is it possible for `neurosift`, or the way you've integrated it, to fail?

And if so, is it possible to catch that failure and instead fallback to the basic HTML display in that event (basically treating this like icing on the cake, but always offering at some some minimal representation of the output)

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by CodyCBakerPhD** [comment]
Actually storybook confirms what happens in event of failure I suppose: https://www.chromatic.com/test?appId=640a4d93e34604f275368983&id=64e38b652c12a1ee283afdde

but IDK if that's because the input to that page is not suitable for the story or what-not

**Comment by garrettmflynn** [comment]
As far as I can think, there is only one case where the Neurosift iframe will fail and we can still get the HTML representation: when there is a bug introduced on the Neurosift site itself that is undesirable.

All other cases (e.g. server down, file not created, etc.) will result in us being unable to get any representation of the file.

**Comment by garrettmflynn** [comment]
As mentioned in the last meeting, the clearest case where this could be useful is when internet is down—so we can't actually gain access to the Neurosift URL.

**Pull request merged**
