### PR TITLE
Improve embargoing and license specification process

### LINKED ISSUE #638: [Feature]: License selection
### What would you like to see added to the NWB GUIDE?

image

The license selection is a bit awkward. Instead of this mechanism, can you just make it checkboxes for each of these? And can you have the strings simply be CC0-1.0 and CC-BY-4.0. Also can you add info boxes with links to supporting documentation:
CC0: https://creativecommons.org/public-domain/cc0/
CC-BY: https://creativecommons.org/licenses/by/4.0/deed.en

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

Yes

### Did you confirm this feature was not already reported?

Yes

### PR DESCRIPTION
**Pull request by garrettmflynn**
fix #638 and #637 

Instead of the direct suggestions in the previous PRs, I have opted to (1) ask a single direct question regarding your Embargo Status, (2) show/hide additional metadata like the NIH Award Number based on the embargo status, and (3) provide a search bar that appends to a list to handle license specification—and updated our tooling with new editors for simple arrays of strings (e.g. keywords).

Let me know if these changes are sufficient to improve the UX, otherwise I can take a stab at the suggestions otherwise proposed in the PRs.

The original suggestions will require some UI  changes that are inconsistent with previous designs (e.g. checkboxes with links, text on the side of the input rather than as a header, etc.), which would just have to be thought out in more detail.

### CODE REVIEW

**Comment by garrettmflynn** [comment]
Here are some related screenshots:

## Embargo
Screenshot 2024-03-08 at 3 19 01 PM

Screenshot 2024-03-08 at 3 19 19 PM

## License
Screenshot 2024-03-08 at 3 19 48 PM

Screenshot 2024-03-08 at 3 19 53 PM

## Keywords
Screenshot 2024-03-08 at 3 20 38 PM

Screenshot 2024-03-08 at 3 21 00 PM

**Comment by CodyCBakerPhD** [comment]
Can the question have Yes/No buttons instead of a checkbox? A little more personable since we're asking an actual question

**Comment by CodyCBakerPhD** [comment]
And I think some of the confusion on the license is the fact that you can have both - legally I'm not even sure how that would work; would the more or less strict one take precedence? Despite it being a `list` in the DANDI schema it might make more sense for now to just limit to just one, which can be selected via a radio or other button selector

**Comment by CodyCBakerPhD** [comment]
Letting @bendichter review this one

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn Though I will note, failing tests on this branch preventing merge once approved

**Comment by bendichter** [comment]
I like this but the red is too red. It implies danger.

**Comment by garrettmflynn** [comment]
Fair. I'll de-emphasize the colors to indicate a neutral choice.

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn Small conflict

**Comment by garrettmflynn** [comment]
@bendichter All requested updates have been made. This should be ready to roll!

**Comment by bendichter** [comment]
@garrettmflynn it looks like you still have some merge conflicts

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
