### PR TITLE
Update daily failure email list

### PR DESCRIPTION
**Pull request by pauladkisson**
Switches to using the github secret for email notifications of daily tests failing.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
This is by choice

https://github.com/NeurodataWithoutBorders/nwb-guide/pull/920#discussion_r1729354847

**Comment by pauladkisson** [comment]
I think with this [sheet](https://docs.google.com/spreadsheets/d/1-84rfEBMbf32o9N5mJj2J8c6wAcrtMgaF0QFTd13S_Y/edit?gid=877719374#gid=877719374) to keep track of secret owners/locations it shouldn't be tough to debug, and then we wouldn't need a PR to add/remove an email.

**Review by rly — APPROVED** [review]

**Comment by rly** [comment]
This is fine to me, though it is not transparent to me who is currently getting emails, so it would be hard to update these secrets. Can I get access to that google sheet? Or we can make a separate one for the NeurodataWithoutBorders repos like nwb-guide and nwbinspector.

**Comment by rly** [comment]
`Add Issue or Pull Request to Dashboard / Add issue or pull request to project (pull_request)` is failing. It looks like this adds an issue/PR to the catalystneuro board. Can you update the token for this, or remove it if it is no longer needed?

**Comment by pauladkisson** [comment]
> This is fine to me, though it is not transparent to me who is currently getting emails, so it would be hard to update these secrets. Can I get access to that google sheet? Or we can make a separate one for the NeurodataWithoutBorders repos like nwb-guide and nwbinspector.

Just shared.

**Pull request merged**
