### PR TITLE
Reload the navigation sidebar from saved project

### PR DESCRIPTION
**Pull request by garrettmflynn**
This PR allows for reloading the navigation sidebar (Guided Mode sidebar) with an accurate history of the pages visited by the users.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
Sorry, I must be missing it - I went back and forth between this branch and `main` a couple times and couldn't see the difference

What specific behavior does this PR enable?

**Comment by garrettmflynn** [comment]
The Guided Mode navigation bar was not reloading progress (i.e. it would not register that you visited pages 1-4 and spit you onto page 5 without the ability to backtrack on the sidebar itself)

**Comment by CodyCBakerPhD** [comment]
Ohhh I see now

For future bug fixes like this, a more step-by-step set of instructions to reproduce the problem on `main` (or even a quick video demonstrating it) helps a lot

Also as soon as you detect something like this feel free to raise an issue first so everyone can be aware of it, and then we can discuss/prioritize it along with everything else on the docket

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by garrettmflynn** [comment]
Alright will do that in the future!

**Pull request merged**
