### PR TITLE
[Frontend Refactor II] Separate stories from src

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
@garrettmflynn This was the next follow-up right? Anything left to do here?

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
Well, besides a massive rebase lol

Despite it being branched from #792 looks like a lot of conflicts

**Comment by garrettmflynn** [comment]
Wasn't too bad to merge. I think we can get this through as-is.

Just FYI, this was a result of merging https://github.com/NeurodataWithoutBorders/nwb-guide/pull/800. Was easy to tell since the merge conflicts span the entire file—indicating that each line had some sort of change associated with it.

**Comment by CodyCBakerPhD** [comment]
> Just FYI, this was a result of merging https://github.com/NeurodataWithoutBorders/nwb-guide/pull/800. Was easy to tell since the merge conflicts span the entire file—indicating that each line had some sort of change associated with it.

Oh, durr.. the other most common source of massive merge conflicts

**Review by garrettmflynn — APPROVED** [review]
Sweet looks good to me

**Comment by CodyCBakerPhD** [comment]
Oof, looks like Chromatic needs some reroutes: https://github.com/NeurodataWithoutBorders/nwb-guide/actions/runs/9277056004/job/25525472646?pr=801

**Comment by garrettmflynn** [comment]
Thanks for pinging me! Looks mostly handled, forgot to review.

**Comment by CodyCBakerPhD** [comment]
Awesome - last PR along these lines was about renaming the subfolders for electron, correct?

**Comment by garrettmflynn** [comment]
Yep! Will tackle that tomorrow :)

**Pull request merged**
