### PR TITLE
Retry on failure

### LINKED ISSUE #613: E2E Tests are Inconsistent
The new end-to-end testing workflow spontaneously fails on a subset of the CI platforms for no predictable reason. 

E.g. https://github.com/NeurodataWithoutBorders/nwb-guide/actions/runs/7879423399/attempts/1?pr=612 failed on Mac because of a timeout issue on the Subject page, whereas Windows failed because of the inability to locate a certain DANDI asset (whose URL appeared to have an extra colon at the end).

**To Reproduce**
Steps that leads to the issue:

1. Create a new branch from `main`
2. Submit a PR
3. Observe the Actions workflow, specifically the backend tests
4. Repeat backend tests until failure

### PR DESCRIPTION
**Pull request by garrettmflynn**
fix #613

This was suggested when merging #612

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
OK, well the action is working: https://github.com/NeurodataWithoutBorders/nwb-guide/actions/runs/7960795322/job/21737344076?pr=617#step:12:575 -> https://github.com/NeurodataWithoutBorders/nwb-guide/actions/runs/7960795322/job/21737344076?pr=617#step:12:1138

But not helping  alleviate the underlying problem...

**Comment by garrettmflynn** [comment]
That specific run has an issue because of `No module named 'flask'`. Seems like the create and activate environment step didn't run.

I've never noticed this become a problem before. Is there a reason this was excluded?

**Comment by CodyCBakerPhD** [comment]
Hmm... Could it be that the action isn't running in the same shell? (one in which the conda environment is not active?)

Adding a printout of the installed packages to be sure; the cache was restored in the logs I linked so you'd hope so

**Comment by garrettmflynn** [comment]
Ah looks like that's the case. Just updated to the same shell.

Fingers crossed!

**Comment by garrettmflynn** [comment]
Hmm all attempts here don't seem to help. According to the docs, this should default to `bash` on Mac and Linux—and otherwise it seems likely that it'd use the default set at the top of the workflow.

**Comment by CodyCBakerPhD** [comment]
Right, but specifying it as `bash` would be a fresh shell I believe, not the currently active conda environment; maybe add a `conda activate nwb-guide` as first step of the `run` command in the retry?

**Comment by CodyCBakerPhD** [comment]
Tabling for now to see if we actually need this - #621 has been working well so far

**Comment by CodyCBakerPhD** [comment]
Yeah I don't think we actually need this any more

**Pull request closed without merging**
