### PR TITLE
Fix initial ReadTheDocs build

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
Completely forgot a couple of essential files RTD needs lol

**Comment by CodyCBakerPhD** [comment]
Voila - the PR integration should be working now. You can always check that doc chhanges render correctly by clicking on the `details` button from the PR checks screen

image

**Review by garrettmflynn — APPROVED** [review]
Looking good. I found the build on Read the Docs itself—and I'm assuming the details button will show up when this is merged with main. Currently don't have one.

**Comment by CodyCBakerPhD** [comment]
> Currently don't have one.

Really? It's not belong the chromatic bot and above the pre-commit, that you can see?

**Comment by garrettmflynn** [comment]
Nevermind. We now have a scrollbar because there are so many checks...my bad!

**Pull request merged**
