### PR TITLE
Add SpikeGadgets Interface

### PR DESCRIPTION
**Pull request by garrettmflynn**
This PR adds support for the SpikeGadgetsRecordingInterface to the GUIDE.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
OK this mostly looks good, but if I manually input `gains` like so

image

then when I reach the end of the metadata form and try to generate preview I get

```javascript
utils.js:35 Uncaught (in promise) Error: Request to convert failed: can't multiply sequence by non-int of type 'float'
    at run (utils.js:35:33)
    at async GuidedMetadataPage.runConversions (Page.js:129:28)
    at async InstanceManager.onClick (GuidedMetadata.js:165:50)
```

**Comment by garrettmflynn** [comment]
This should be handled more gracefully after merging #249, though I can implement a quick fix to recognize lists of numbers and convert them properly.

**Comment by garrettmflynn** [comment]
I've done as much as I can on my end.


Though this is actually a problem with the schema for the SpikeGadgetsRecordingInterface, which specifies that `gains` should be an array but doesn't indicate the type of items contained within it:
Screenshot 2023-08-08 at 2 32 17 PM

**Comment by CodyCBakerPhD** [comment]
Ahhh, yes. I see the problem.

Would you prefer to use this solution or await the correct on the NeuroConv side?

**Comment by garrettmflynn** [comment]
So the latest changes actually depend on those `neuroconv` corrections to work. Once those are applied, though, this should be fine.

The only stand-in solution would be to use `try / catch` to determine if a certain input could be parsed as a number, then use that numeric value instead if it can.

**Comment by CodyCBakerPhD** [comment]
OK, might as well table it alongside the TDT fix as well then

**Comment by garrettmflynn** [comment]
Updated this since @stephprince wanted to use it. We have an issue in NeuroConv where Gains isn't specified explicitly, otherwise this should be good to go:
Screenshot 2024-04-18 at 2 58 56 PM

**Comment by CodyCBakerPhD** [comment]
Right, that's the trouble with this interface

It needs a a list of float gains to be specified

But the length of the list we cannot know until we know the file path and try to read it, so validation and typing is tricky

**Comment by CodyCBakerPhD** [comment]
Awaiting ongoing work between the Frank lab and neo to resolve the stream issues

**Pull request closed without merging**
