### PR TITLE
Add EDF

### PR DESCRIPTION
**Pull request by garrettmflynn**
Add the EDFRecordingInterface to the list of accepted interfaces.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn Do you run into any errors regarding file I/O when you reach the final step using this interface? Just checking if it's platform dependent

**Comment by garrettmflynn** [comment]
I can't get past the GuidedSourceData page because of the following issue: 
```
cannot import name 'Tester' from 'numpy.testing'
```

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn Interesting... does that happen if you regenerate a fresh conda environment?

**Comment by CodyCBakerPhD** [comment]
Moving to draft until further investigation and possible fix is found

**Comment by CodyCBakerPhD** [comment]
Ohhhh, huh... right you are

Just waiting 4-5 seconds clears it up. How weird

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
