### PR TITLE
Add CellExplorerRecordingInterface

### PR DESCRIPTION
**Pull request by garrettmflynn**
This PR attempts to add the CellExplorerRecordingInterface. However, an error on the standard test files blocks us from going further than the Source Data page:

Screenshot 2023-10-17 at 2 30 50 PM

## Full Error
[main-process]: [2023-10-17 14:30:42,691] ERROR in app: Exception on /neuroconv/metadata [POST]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/nwb-guide/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/anaconda3/envs/nwb-guide/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/anaconda3/envs/nwb-guide/lib/python3.9/site-packages/flask_restx/api.py", line 404, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/anaconda3/envs/nwb-guide/lib/python3.9/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/opt/anaconda3/envs/nwb-guide/lib/python3.9/site-packages/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/garrettflynn/Documents/Github/nwb-guide/pyflask/apis/neuroconv.py", line 77, in post
    return get_metadata_schema(neuroconv_api.payload.get("source_data"), neuroconv_api.payload.get("interfaces"))
  File "/Users/garrettflynn/Documents/Github/nwb-guide/pyflask/manageNeuroconv/manage_neuroconv.py", line 205, in get_metadata_schema
    converter = instantiate_custom_converter(source_data, interfaces)
  File "/Users/garrettflynn/Documents/Github/nwb-guide/pyflask/manageNeuroconv/manage_neuroconv.py", line 168, in instantiate_custom_converter
    return CustomNWBConverter(source_data)
  File "/opt/anaconda3/envs/nwb-guide/lib/python3.9/site-packages/neuroconv/nwbconverter.py", line 65, in __init__
    self.data_interface_objects = {
  File "/opt/anaconda3/envs/nwb-guide/lib/python3.9/site-packages/neuroconv/nwbconverter.py", line 66, in <dictcomp>
    name: data_interface(**source_data[name])
  File "/opt/anaconda3/envs/nwb-guide/lib/python3.9/site-packages/neuroconv/datainterfaces/ecephys/cellexplorer/cellexplorerdatainterface.py", line 304, in __init__
    session_data = read_mat(filename=session_data_file_path, ignore_fields=ignore_fields)["session"]
  File "/opt/anaconda3/envs/nwb-guide/lib/python3.9/site-packages/pymatreader/pymatreader.py", line 87, in read_mat
    mjv, _ = matfile_version(fid)
  File "/opt/anaconda3/envs/nwb-guide/lib/python3.9/site-packages/scipy/io/matlab/_miobase.py", line 221, in matfile_version
    return _get_matfile_version(fileobj)
  File "/opt/anaconda3/envs/nwb-guide/lib/python3.9/site-packages/scipy/io/matlab/_miobase.py", line 243, in _get_matfile_version
    maj_ind = int(tst_str[2] == b'I'[0])
IndexError: index out of range

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
Weird, since that's the same one used in the tests: https://github.com/catalystneuro/neuroconv/blob/main/tests/test_on_data/test_recording_interfaces.py#L93C15-L93C15

Pinging @h-mayorquin since he put that interface together

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin any ideas on this one?

**Comment by h-mayorquin** [comment]
It seems like a scipy version thing?

Which environment is used to run those tests?

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin It varies by platform, for the most part is the same as NeuroConv, but in this case I assume it's the one from the following config file

https://github.com/NeurodataWithoutBorders/nwb-guide/blob/main/environments/environment-MAC.yml

**Comment by garrettmflynn** [comment]
@CodyCBakerPhD Just tested this and updating with datalad allows me to move forward. Looks like this'll be good then!

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
