### PR TITLE
Edit arbitrary arrays on the JSON Schema Form

### PR DESCRIPTION
**Pull request by garrettmflynn**
This PR allows for you to edit arrays with arbitrary content as long as their `items` schema value describes something that is itself editable on its own.

This was discovered as a requirement when attempting to add the `AudioInterface` and other behavioral interfaces to the GUIDE, which accept a list of `file_paths`.

The appropriate updates have been made to the JSONSchemaForm Storybook entry so that you can view the results in Chromatic or interact with it directly.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
When making a new pipeline on this branch, I cannot assign a project name because that field does not populate

image

**Comment by CodyCBakerPhD** [comment]
Similarly, when I go to a pre-existing pipeline, I cannot enter an experimenter after clicking the button because no text field renders

image

**Comment by CodyCBakerPhD** [comment]
Arriving at the file metadata page for the tutorial blasts this stack to the console, and I'm unable to proceed to the conversion preview

```javascript
JSONSchemaForm.js:565 Uncaught (in promise) ReferenceError: f is not defined
    at #getLinkElement (JSONSchemaForm.js:565:9)
    at JSONSchemaForm.triggerValidation (JSONSchemaForm.js:631:48)
    at async #checkRequiredAfterChange (JSONSchemaForm.js:368:25)
    at async required.<computed> (JSONSchemaForm.js:401:47)

Uncaught (in promise) ReferenceError: f is not defined
    at #getLinkElement (JSONSchemaForm.js:565:9)
    at JSONSchemaForm.triggerValidation (JSONSchemaForm.js:631:48)
```

which repeats ~10 times

**Comment by CodyCBakerPhD** [comment]
The save button doesn't seem to be working w.r.t. the preview button here

If I add two items to experimenter; 'Baker, Cody' and 'Flynn, Garrett' then try to preview the file, they are not added. Pressing the save button then re-attempting also does not solve the issue

If I hit the 'Run Conversion Preview' button then it does successfully save whatever info I added to the page

If you think this is a broader issue with the save button independent of this PR, then let me know and a fix can go in a separate PR

**Comment by garrettmflynn** [comment]
Your intuition was correct. This is an issue with the implementation of the save button, which is now fixed in #261 since it now is session-specific

**Comment by CodyCBakerPhD** [comment]
OK then - the rest of this PR looks fine then - can you fix the issues in the tests and this should be good to go

**Comment by CodyCBakerPhD** [comment]
Looks like I botched a merge conflict from updating from #282 at lines https://github.com/NeurodataWithoutBorders/nwb-guide/pull/249/files#diff-b61cebbe905559bcb94378221585dc13cd4b81d2b633c18eba3cbcaca9061d78L296-R258

So sorry

If I change it back to `#update` the app at least launches but the saving/updating/preview behavior still doesn't seem to work

It also doesn't flag validation of bad experimenter form

Not sure if those are because of the improper conflict resolution or not

**Comment by garrettmflynn** [comment]
Fixed the merge issue.

**Comment by garrettmflynn** [comment]
Tests are passing now as well!

**Comment by CodyCBakerPhD** [comment]
The changes themselves look good - what seems to have gone a bit off on this branch is the inclusion of this entire `coverage` folder, which I'm fairly sure should have been ignored by git...

Can @rly or you confirm, and if so remove it from this PR? Then we'll squash on merge

**Comment by garrettmflynn** [comment]
Yeah I don't think we need it. Just removed

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
