### PR TITLE
Fix Upload BeforeSave Callback

### LINKED ISSUE #357: [Bug] DANDI Upload via final guided mode page
Might be Mac specific - haven't tried other platforms yet

Ran through a fresh tutorial in dev mode, worked fine until I reached the final DANDI upload page

I specified my staging dandiset ID but this error was thrown to dev console

```javascript
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'dandiset_id')
    at GuidedUploadPage.beforeSave (GuidedUpload.js:20:50)
    at GuidedUploadPage.save (Page.js:96:39)
    at GuidedFooter.onNext [as __onNext] (GuidedUpload.js:28:24)
    at EventPart.handleEvent (lit-html.ts:2003:29)
beforeSave @ GuidedUpload.js:20
save @ Page.js:96
onNext @ GuidedUpload.js:28
handleEvent @ lit-html.ts:2003
await in handleEvent (async)
handleEvent @ lit-html.ts:2003
```

### PR DESCRIPTION
**Pull request by garrettmflynn**
fix #357

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
That resolved that issue, now on to

```javascript
ncaught (in promise) Error: Request to upload/folder failed: upload_folder_to_dandi() got an unexpected keyword argument 'project'
    at run (utils.js:35:33)
    at async GuidedUploadPage.uploadToDandi (UploadsPage.js:32:12)
    at async GuidedFooter.onNext [as __onNext] (GuidedUpload.js?t=1694567791220:50:29)
```

**Comment by garrettmflynn** [comment]
I was seeing this before if I didn't start a new conversion. Can you try that?

**Comment by CodyCBakerPhD** [comment]
> I was seeing this before if I didn't start a new conversion. Can you try that?

Yep, confirmed with an entirely newly generated tutorial pipeline

Will try a non-tutorial one now

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn If it's any help at giving more context, I always seem to get this screen even if it is definitely the first time I've ever tried uploading this session

image

**Comment by CodyCBakerPhD** [comment]
And yeah, same issue again in a custom pipeline once I press that 'continue with reupload' button

**Comment by garrettmflynn** [comment]
Okay thanks for the context. I’ll try on my end

**Comment by garrettmflynn** [comment]
Alright this is fixed and merged with `main`

**Comment by CodyCBakerPhD** [comment]
Tested both guided mode page and stand alone page - both worked great!

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
