### PR TITLE
Ensure conversions are synced

### PR DESCRIPTION
**Pull request by garrettmflynn**
This PR ensures that pages that are dependent on certain resolved features can trigger behaviors to create those features. Specifically, the Inspect and Neurosift pages now check for whether the stub files are up-to-date with the latest changes made in the GUIDE (e.g. if someone reviews the Inspector report, makes changes, and revisits without passing through the File Metadata page). 

## User Test Issue
1. Not clear that you have to go back to File Metadata to regenerate the stub / conversion files…

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn Some conflicts here now

**Comment by CodyCBakerPhD** [comment]
The left nav bar now reads as

Screenshot 2023-11-10 at 10 51 44 PM

which is confusing - is this an intended change?

**Comment by garrettmflynn** [comment]
This was a noted consequence of #497. This should go away by reloading and starting a new conversion.

**Comment by CodyCBakerPhD** [comment]
Ah, right. Swapped devices since then and forgot to wipe all the ones on my new device

**Comment by CodyCBakerPhD** [comment]
OK this feels like a good interaction!

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
