### PR TITLE
Hot reload with Electron

### PR DESCRIPTION
**Pull request by garrettmflynn**
This PR allows for immediate reflection of changes to the code in the Electron app (similar to the web version) with minimal load-time.

### CODE REVIEW

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by CodyCBakerPhD** [comment]
IDK why but this took me forever to install with `npm ci`

**Comment by CodyCBakerPhD** [comment]
Also can't quite get the reload functionality to work as I would have expected (I change some code on the Flask backend, hit reload, and the change does not apply to the app unless I quite and re-launch)

But if it's working for you go ahead and merge

**Comment by garrettmflynn** [comment]
This is just looking at the JavaScript code. I can see if it will watch Python code as well.

**Comment by CodyCBakerPhD** [comment]
> This is just looking at the JavaScript code.

Ah, that would explain why lol


> I can see if it will watch Python code as well.

Let me know if that works - if so, it could act as a really convenient way of doing certain dynamic imports/installs going into the future

**Comment by garrettmflynn** [comment]
@CodyCBakerPhD So [`electron-reloader`](https://github.com/sindresorhus/electron-reloader) does not allow for manual configuration of what to watch, though their code would be quite simple to replicate ourselves using [`chokidar`](https://github.com/paulmillr/chokidar). 

I've opened a new Issue (#136) where we can talk about the "certain dynamic imports/installs" in more detail and see if we'd like a custom solution.

**Pull request merged**
