### PR TITLE
Selectively Enable Source Data Interfaces

### PR DESCRIPTION
**Pull request by garrettmflynn**
This PR generally allows for removing non-required schema object properties (e.g. Interfaces on the source data page) so that they are saved but not passed to subsequent parts of the workflow such as the server.

Specifically, this has been tested with regard to selective enabling / disabling Interfaces across several sessions.

A uniform accordion-style rendering system is now used across all forms, including Global forms like NWBFile and Subject Global Metadata, allowing for us to display the status (error, warning, valid) of those forms as we go.

## User Testing Issues
1. need to add a way for source data to not be required (for an interface to be deleted) at the session level rather than just the data formats page - in case one particular session does not have a certain file/folder available

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
Looks like validation isn't filtering out the unselected ones

image

otherwise, the appearance of the selector feels fine and the earlier pages, though on initial appearance are a little odd looking outside the context of the session manager, are at least consistent with the later sections (including the later 'localized' global metadata popups)

**Comment by garrettmflynn** [comment]
Ah good catch. Should be a simple fix

**Comment by garrettmflynn** [comment]
Hmmm I'm not able to replicate this. Maybe you can show me at our meeting?

Are there two sessions or just one here?

**Comment by garrettmflynn** [comment]
@CodyCBakerPhD Alright tests should pass now.

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn A couple of conflicts with `main` now

**Comment by CodyCBakerPhD** [comment]
Workflow:

select several interfaces -> define several sessions -> specify a mixture of source files and disabled interfaces for each session -> try to proceed

Screen appears as

image

but received error

```python
Exception on /neuroconv/metadata [POST]
Traceback (most recent call last):
  File "D:\anaconda3\envs\nwb-guide\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda3\envs\nwb-guide\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\anaconda3\envs\nwb-guide\lib\site-packages\flask_restx\api.py", line 404, in wrapper
    resp = resource(*args, **kwargs)
  File "D:\anaconda3\envs\nwb-guide\lib\site-packages\flask\views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "D:\anaconda3\envs\nwb-guide\lib\site-packages\flask_restx\resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "D:\GitHub\nwb-guide\pyflask\apis\neuroconv.py", line 84, in post
    return get_metadata_schema(neuroconv_api.payload.get("source_data"), neuroconv_api.payload.get("interfaces"))
  File "D:\GitHub\nwb-guide\pyflask\manageNeuroconv\manage_neuroconv.py", line 254, in get_metadata_schema
    converter = instantiate_custom_converter(source_data, interfaces)
  File "D:\GitHub\nwb-guide\pyflask\manageNeuroconv\manage_neuroconv.py", line 217, in instantiate_custom_converter
    return CustomNWBConverter(source_data)
  File "D:\GitHub\neuroconv\src\neuroconv\nwbconverter.py", line 64, in __init__
    self._validate_source_data(source_data=source_data, verbose=self.verbose)
  File "D:\GitHub\neuroconv\src\neuroconv\nwbconverter.py", line 107, in _validate_source_data
    validate(instance=source_data, schema=self.get_source_schema())
  File "D:\anaconda3\envs\nwb-guide\lib\site-packages\jsonschema\validators.py", line 1306, in validate
    raise error
jsonschema.exceptions.ValidationError: Additional properties are not allowed ('__disabled' was unexpected)
```

**Comment by garrettmflynn** [comment]
Forgot to remove the semi-private (__) properties. Should work now that they aren't sent to the server

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by CodyCBakerPhD** [comment]
LGTM

**Pull request merged**
