### PR TITLE
[Simplify PyFlask III]: remove setupUtils and unused startup endpoint(s)

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
Do we still need the echo endpoint in 'startup'? Do we ever use it? If not we can get rid of that sub namespace completely

### CODE REVIEW

**Comment by garrettmflynn** [comment]
We do use it for checking if the Python server is actually started. We could simply maintain a variable in the `main` Electron process and pass this on completion—but actually getting a request to pass is the most foolproof method.

**Comment by CodyCBakerPhD** [comment]
Ohhh right you are: https://github.com/NeurodataWithoutBorders/nwb-guide/blob/ea8fa6fc09112a99cad305b9e5a32af87695951c/src/renderer/src/index.ts#L128-L134

OK fine to keep then

**Comment by garrettmflynn** [comment]
The alternative approach may actually allow us to catch a failed Python server rather than simply waiting for a timeout. Would we want to pursue that approach or nah?

**Comment by CodyCBakerPhD** [comment]
> We could always send the echo request when notified to double-check.

I defer to you on the approaches that might be best for detecting such an event

In general I don't mind doing all of them, or as many as are useful for detecting different points of failure

My general approach right now is also just to massively simplify what is required to run the Flask server itself as opposed to the question of what is required to operate individual endpoint commands

**Comment by garrettmflynn** [comment]
Okay sounds good. Will file this away as a possible improvement for later.

**Comment by garrettmflynn** [comment]
Implemented on #301 to Implemented on #301 to help with debugging the Mac and other builds.

**Review by garrettmflynn — APPROVED** [review]
Looks good to me. Not using any of the deleted endpoints and the flattened app structure looks much better.

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn Sorry, need re-approval on this. I've disabled the stale dismission moving forward

**Review by garrettmflynn — APPROVED** [review]
No worries. Let's merge it in!

**Pull request merged**
