### PR TITLE
Modularize Inspector Preview

### PR DESCRIPTION
**Pull request by garrettmflynn**
This PR builds on #326 by (1) breaking out an Inspect Files page from the Preview Files page, (2) aggregating messages in a way that is more consistent with the NWB Inspector text printout, and (3) allowing users to filter messages by subject, subject + session, or not at all.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
New preview page looks great

But I see leftover tabs on the left bar, which were not navigated to during the normal workflow of pressing each bottom right green button

image

**Comment by CodyCBakerPhD** [comment]
The Inspection feels way faster now BTW, and I confirmed by watching my task manager that extra Python instances were indeed spawned by the parallelized inspection

**Comment by garrettmflynn** [comment]
Can you start the pipeline from scratch and try again?

From my experience, this should just be holdover from previous runs—but let
me know if that doesn’t fix the problem.

**Comment by CodyCBakerPhD** [comment]
Oh, yeah sorry

```javascript
Uncaught TypeError: Cannot read properties of undefined (reading 'join')
    at getSharedPath (NWBFilePreview.js:23:34)
    at All Files (GuidedInspectorPage.js:114:42)
    at #onSelected (InstanceManager.js:275:67)
    at item.onClick (InstanceManager.js:341:37)
    at #onClick (item.ts:138:14)
    at html.onRemoved.html.padding (item.ts:153:46)
    at EventPart.handleEvent (lit-html.ts:2003:29)
getSharedPath @ NWBFilePreview.js:23
All Files @ GuidedInspectorPage.js:114
#onSelected @ InstanceManager.js:275
item.onClick @ InstanceManager.js:341
#onClick @ item.ts:138
html.onRemoved.html.padding @ item.ts:153
handleEvent @ lit-html.ts:2003
```

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
