### PR TITLE
Electron vite reload

### PR DESCRIPTION
**Pull request by garrettmflynn**
fix #133 and #136

This PR implements hot reloading for Electron (for real this time...) and Python. Because of the suggested structure for `electron-vite`, it requires a significant refactor of the project structure.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
> Because of the suggested structure for electron-vite, it requires a significant refactor of the project structure.

That last bit means this is likely to cause an awful lot of conflicts. How would you like to proceed? I can review all the other ones first then come back to this?

**Comment by garrettmflynn** [comment]
Let’s do that. Depending on the complexity, I can redo this PR and stop
submitting PRs until it is approved—since I’ve worked out a predictable
process for doing the refactor.

**Comment by garrettmflynn** [comment]
Fixed. I’d saved the modified path internally but didn’t pass it through
the callback that updates the globalState

**Comment by garrettmflynn** [comment]
Definitely, as it touched a lot of files. Thanks for checking about it

**Comment by CodyCBakerPhD** [comment]
OK ready to try this again

After this is done, I'll re-enable prettier through pre-commit and then we can start fresh branches again

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
