### PR TITLE
Add AudioInterface

### PR DESCRIPTION
**Pull request by garrettmflynn**
This PR adds the AudioInterface to the GUIDE, which passes on the test data.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
Is there a reason to suddenly start exposing the metadata for `Behavior` on this PR? If so, this will take a little bit of back and forth to polish

**Comment by garrettmflynn** [comment]
No I just didn't make much of it because it didn't fail on the test data. I blocked this on the VideoInterface, I think, so can bring those changes out to a separate PR?

**Comment by CodyCBakerPhD** [comment]
I would suppress the metadata for now

Despite how simple it looks there's actually things I'd want to change about it, plus it magnifies the complexity of things to test in this PR

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by CodyCBakerPhD** [comment]
Looks good 👍

**Pull request merged**
