### PR TITLE
Trying to fix Windows and Linux distributable 

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
Trying to fix windows side of current distributable errors related to Pydantic

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn 3 tests are passing according to log output for Windows here: https://github.com/NeurodataWithoutBorders/nwb-guide/actions/runs/6102263434/job/16560353693?pr=346

But CI itself is failing and says there are 'Errors' without reasons or tracebacks, any idea how to interpret this?

**Comment by garrettmflynn** [comment]
This looks like it's fine. The executable test suite finishes without issue, causing the `.exe` to close—though this action seems to be something that registers as an error for the workflow. 

The only outstanding issue is that an Error Code 1 is thrown by the latter. Not sure why or how we could figure that out—but I'll look into it

**Comment by CodyCBakerPhD** [comment]
> This looks like it's fine. The executable test suite finishes without issue, causing the .exe to close—though this action seems to be something that registers as an error for the workflow.
>
> The only outstanding issue is that an Error Code 1 is thrown by the latter. Not sure why or how we could figure that out—but I'll look into it

Fantastic! Exciting.

Yeah if you can figure out how to make the CI give the glorious green check that would be great, then I'll move onto the other platforms

**Comment by garrettmflynn** [comment]
Found a solution on this issue: https://github.com/open-cli-tools/concurrently/issues/187

Turns out this is a common problem, I'd tried using the `--success` flag originally but it turns out `first` means the first to _exit_ when I thought it meant the first process in the list of those to run

**Comment by garrettmflynn** [comment]
@CodyCBakerPhD Worked for both Windows and Linux! Unfortunately, we're running into the same Mac issue that @rly  originally solved in #89...

**Comment by CodyCBakerPhD** [comment]
> @CodyCBakerPhD Worked for both Windows and Linux! Unfortunately, we're running into the same Mac issue that @rly originally solved in https://github.com/NeurodataWithoutBorders/nwb-guide/issues/89...

Awesome, thanks a bunch! We can tackle Mac in a follow-up then

**Review by rly — APPROVED** [review]

**Pull request merged**
