### PR TITLE
Add MicroManagerTiffImagingInterface

### PR DESCRIPTION
**Pull request by garrettmflynn**
This PR adds the MicroManagerTiffImagingInterface. The first pass through this interface, however, reveals an issue where **JavaScript does not maintain float values with trailing zeros** so the value of `imaging_rate` in JSON is `20.0` (float), which gets converted to `20` in JS (number) and passed back to Python as `20` (int).

Do we need to correct for int-like floats like we do for expected NaN values?

## Error
```

[2023-09-28 13:17:03,870] ERROR in app: Exception on /neuroconv/convert [POST]
Traceback (most recent call last):
  File "/Users/garrettflynn/Documents/Github/nwb-guide/pyflask/apis/neuroconv.py", line 82, in post
    return convert_to_nwb(neuroconv_api.payload)
  File "/Users/garrettflynn/Documents/Github/nwb-guide/pyflask/manageNeuroconv/manage_neuroconv.py", line 383, in convert_to_nwb
    converter.run_conversion(
  File "/opt/anaconda3/envs/nwb-guide/lib/python3.9/site-packages/neuroconv/nwbconverter.py", line 160, in run_conversion
    self.add_to_nwbfile(nwbfile_out, metadata, conversion_options)
  File "/opt/anaconda3/envs/nwb-guide/lib/python3.9/site-packages/neuroconv/nwbconverter.py", line 114, in add_to_nwbfile
    data_interface.add_to_nwbfile(
  File "/opt/anaconda3/envs/nwb-guide/lib/python3.9/site-packages/neuroconv/datainterfaces/ophys/baseimagingextractorinterface.py", line 118, in add_to_nwbfile
    add_imaging(
  File "/opt/anaconda3/envs/nwb-guide/lib/python3.9/site-packages/neuroconv/tools/roiextractors/roiextractors.py", line 492, in add_imaging
    add_photon_series(
  File "/opt/anaconda3/envs/nwb-guide/lib/python3.9/site-packages/neuroconv/tools/roiextractors/roiextractors.py", line 364, in add_photon_series
    nwbfile = add_imaging_plane(nwbfile=nwbfile, metadata=metadata_copy, imaging_plane_index=photon_series_index)
  File "/opt/anaconda3/envs/nwb-guide/lib/python3.9/site-packages/neuroconv/tools/roiextractors/roiextractors.py", line 251, in add_imaging_plane
    imaging_plane = _create_imaging_plane_from_metadata(
  File "/opt/anaconda3/envs/nwb-guide/lib/python3.9/site-packages/neuroconv/tools/roiextractors/roiextractors.py", line 214, in _create_imaging_plane_from_metadata
    imaging_plane = ImagingPlane(**imaging_plane_metadata)
  File "/opt/anaconda3/envs/nwb-guide/lib/python3.9/site-packages/hdmf/utils.py", line 643, in func_call
    pargs = _check_args(args, kwargs)
  File "/opt/anaconda3/envs/nwb-guide/lib/python3.9/site-packages/hdmf/utils.py", line 636, in _check_args
    raise ExceptionType(msg)
TypeError: ImagingPlane.__init__: incorrect type for 'imaging_rate' (got 'int', expected 'float')

```

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
> Do we need to correct for int-like floats like we do for expected NaN values?

Yep, looks like; we def need them to be floats after rehydrating

**Comment by garrettmflynn** [comment]
@CodyCBakerPhD Just published that PR. Looks like it works!

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn Oh no 😆 putting fix PR # in the header of the base PR caused this to auto close lol

**Comment by CodyCBakerPhD** [comment]
Indeed works great

**Pull request merged**
