### PR TITLE
[Simplify PyFlask V]: full local scope for all utils

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
This should fix the scipy problem with regards to the Flask server launching

It does _not_ fix the actual problem when the import is triggered by an endpoint that needs to run a Python function using any library stemming from HDMF, but at least this gives us a better capacity to debug live on the Flask server

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
Windows passing, Linux awaiting hopeful fix on #284

**Comment by garrettmflynn** [comment]
Still have that issue with `pydantic[email]`. Maybe that will also go away?

**Comment by CodyCBakerPhD** [comment]
> Still have that issue with pydantic[email]. 

That should even have been fixed as of #296 

Can you re-setup your environment and re-build the build/dist from scratch and then include full traceback for this branch?

Nothing anywhere should be triggering it on launch since the import is only ever triggered on call to the upload endpoint

**Comment by CodyCBakerPhD** [comment]
Oh wow, it's actually in the CI over on https://github.com/NeurodataWithoutBorders/nwb-guide/actions/runs/5905804597/job/16020592221?pr=284

investigating...

**Comment by CodyCBakerPhD** [comment]
Oh I see. Outer import of YAML functionality

https://github.com/catalystneuro/neuroconv/blob/main/src/neuroconv/__init__.py#L5

triggers some minimal DANDI import

https://github.com/catalystneuro/neuroconv/blob/main/src/neuroconv/tools/yaml_conversion_specification/yaml_conversion_specification.py#L7-L8

Sorry I missed that

The conclusion is that #284 will need this branch then to fully resolve that launch issue; fix for using the endpoint remains elusive but the recent front-end additions will at least let the person know why they can't do that one step inside the GUIDE

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn All green

We can even, for the first time, check this with CI deployment to the release page

Parts of the Guided Mode may not work on all platforms, which is still next steps to debug, but this gives us a better position to debug and potentially fix those dynamically using #300 if it works

**Review by garrettmflynn — APPROVED** [review]
Woohoo! Good thinking with this, let's see what we can do

**Pull request merged**
