### PR TITLE
Create Dandisets from the GUIDE

### LINKED ISSUE #221: Create Dandisets using the REST API
Instead of going to [dandiarchive.org](http://dandiarchive.org/), it would be ideal to create dandisets from the GUIDE itself by supplying a name and description on the `upload` page.

### PR DESCRIPTION
**Pull request by garrettmflynn**
fix #221 using the Electron-specific fix linked on https://github.com/dandi/dandi-archive/issues/1640

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
1. First, the button wasn't easy to spot up in the corner. I kind of knew to go looking for it, but I'd like to recommend a routing page that could also pave the way for adding future features like the [llmsearch.dandiarchive.org](https://llmsearch.dandiarchive.org/) integration, an 'edit dandiset metadata' page that goes well beyond the UX of the existing website, an 'upload files to existing dandiset' page, and of course this PR, the 'create new dandiset' page (maybe create can be create OR edit existing due to overlap in metadata between the two...)

@garrettmflynn If you agree, could you start a mockup of a Figma for such a landing page page? 

2. Aside from that, a rather odd window nesting - the 'keywords' of the dandiset creation page (3 windows deep) gets pushed to the side

image

3. And finally, this bug when I hit the 'Create' button

```javascript
TypeError: dandi.API is not a constructor
    at Button.onClick [as __onClick]
```

**Comment by garrettmflynn** [comment]
For (3), you'll have to reinstall your dependencies as one was bumped.

**Comment by garrettmflynn** [comment]
Just fixed (2). Good catch!

**Comment by garrettmflynn** [comment]
@CodyCBakerPhD I'll need a bit more information as to what we'll be looking for to complete (1).

To make Upload Files to Existing Dandiset and this new Create Dandiset option more interchangeable and obvious, I could simply move the Create Dandiset button directly next to the input—though this seems like this might not encapsulate the requirements you have for new features (e.g. LLM search) and editing existing Dandiset metadata.

So here are some questions:

1. What operations do we want to do on existing Dandiset metadata? 
      - Maybe I missed something from earlier discussions, but this seems out of scope from what I see on the milestones and have heard from prior discussions.
2. Would this "button by input" approach work for the LLM search too?
      - As I see it, this modal-based presentation of additional layers is fairly extensible. The main reason we'd want to create different views (e.g. on tabs) would be to separate a Basic vs. Advanced mode that both have standalone—rather than additive—functionality at different levels of control

I'm definitely open to re-designing this page in full—though I want to make sure we fully capture all our current and future needs. 

This sounds like it might be a great conversation for our meeting tomorrow or the next NWB GUIDE meeting :)

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn Any updates on this? From last meeting we decided an even simpler approach of having the input field be 'dandiset' and it having a loose selector (allow free text for back-compatability) that displays the six-digit ID as well as the current name given to the dataset of all currently existing datasets attributed to that users API key (which I guess must be specified before navigating to this page at all - maybe pop-up should trigger on page load then)

Then if they want to create a new dataset, they just give it a custom name and we create for them (then it shows up in the selector next time they try to upload to it)

**Comment by garrettmflynn** [comment]
Been getting settled back at home. Will start on this today!

**Comment by garrettmflynn** [comment]
This should be good for review! All related features have been added.

**Comment by CodyCBakerPhD** [comment]
When I try regenerating a new tutorial dataset on this branch I get

```javascript
Uncaught (in promise) TypeError: urilib.resolve is not a function
    at Validator2.validate (validator.js:118:21)
    at JSONSchemaForm.triggerValidation (JSONSchemaForm.js:705:14)
    at #triggerValidation (JSONSchemaInput.js:166:76)
    at FilesystemSelector.onChange (JSONSchemaInput.js:213:84)
    at FilesystemSelector.<anonymous> (FileSystemSelector.js:96:52)
    at JSONSchemaInput.updated (JSONSchemaInput.js:172:16)
    at JSONSchemaInput._$didUpdate (reactive-element.ts:1378:10)
    at JSONSchemaInput.performUpdate (reactive-element.ts:1343:12)
    at JSONSchemaInput.scheduleUpdate (reactive-element.ts:1261:17)
    at JSONSchemaInput.__enqueueUpdate (reactive-element.ts:1233:25)
```

which throws 4 times in succession

```javascript
browser-external:url:9 Module "url" has been externalized for browser compatibility. Cannot access "url.resolve" in client code. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
```

also pops up in yellow in between the errors

**Comment by CodyCBakerPhD** [comment]
From testing on the standalone page however;

- I love how responsive the loose selector is - the filtering capabilities are really nice
- The new 'Additional Settings' is nice to hide the advanced functionality

**Comment by CodyCBakerPhD** [comment]
Though I run into the same issue as tutorial generation why I actually try to upload

Trying to see if `npm ci` improves anything

**Comment by CodyCBakerPhD** [comment]
Though selecting one of the options from the dropdown allows for a succesful upload

When a DANDI set is created in this way, how does it know which archive to create it on? (main or staging)

**Comment by garrettmflynn** [comment]
> When a DANDI set is created in this way, how does it know which archive to create it on? (main or staging)

The user manually selects whether to upload to staging or main on the Dandiset Metadata popup, where `staging` is currently defaulting to `true`.

**Comment by garrettmflynn** [comment]
> Yeah, OK - it was just an environment issue
> 
> However, upload attempting to create a dandiset I get
> 
> ```js
> Uncaught (in promise) Error: <b>Dandiset</b> is not defined
>     at JSONSchemaForm.throw (JSONSchemaForm.js:363:15)
>     at JSONSchemaForm.validate (JSONSchemaForm.js:410:32)
>     at async GuidedFooter.onNext [as __onNext] (GuidedUpload.js:87:13)
> ```
> 
> and right above it in yellow
> 
> ```js
> Disagreement about the correct error to throw...
> validate @ JSONSchemaForm.js:393
> ```

Can you show me the Dandiset you're trying to create here (i.e. the screen at creation time)?

**Comment by CodyCBakerPhD** [comment]
> The user manually selects whether to upload to staging or main on the Dandiset Metadata popup, where staging is currently defaulting to true.

I saw no such popup

I also wouldn't default, and would perhaps do something like highlighting the the staging server in a yellow or other indicative color of developers/testers to make it clear most actual users would want the actual archive while most people 'playing around with it' would want staging

Screenshot

image

New error this time though

```python
Exception on /neuroconv/upload [POST]
Traceback (most recent call last):
  File "D:\GitHub\nwb-guide\pyflask\apis\neuroconv.py", line 185, in post
    return upload_multiple_filesystem_objects_to_dandi(**neuroconv_api.payload)
  File "D:\GitHub\nwb-guide\pyflask\manageNeuroconv\manage_neuroconv.py", line 475, in upload_multiple_filesystem_objects_to_dandi
    result = upload_folder_to_dandi(**innerKwargs)
  File "D:\GitHub\nwb-guide\pyflask\manageNeuroconv\manage_neuroconv.py", line 493, in upload_folder_to_dandi
    return automatic_dandi_upload(
  File "D:\anaconda3\envs\nwb-guide\lib\site-packages\neuroconv\tools\data_transfers.py", line 329, in automatic_dandi_upload
    dandi_download(urls=dandiset_url, output_dir=str(dandiset_folder_path), get_metadata=True, get_assets=False)
  File "D:\anaconda3\envs\nwb-guide\lib\site-packages\dandi\download.py", line 90, in download
    parsed_urls = [parse_dandi_url(u, glob=path_type == "glob") for u in urls]
  File "D:\anaconda3\envs\nwb-guide\lib\site-packages\dandi\download.py", line 90, in <listcomp>
    parsed_urls = [parse_dandi_url(u, glob=path_type == "glob") for u in urls]
  File "D:\anaconda3\envs\nwb-guide\lib\site-packages\dandi\dandiarchive.py", line 710, in parse
    return cls.parse(new_url, map_instance=map_instance, glob=glob)
  File "D:\anaconda3\envs\nwb-guide\lib\site-packages\dandi\dandiarchive.py", line 717, in parse
    raise RuntimeError(
RuntimeError: https://dandiarchive.org/dandiset/Make%20a%20new%20one/draft did not redirect to another location which dandi client would know how to handle.
```

**Comment by garrettmflynn** [comment]
Whoops I was only catching the new dandiset stuff in Guided Mode (where I was testing). I moved that aspect into the shared upload function—so it is now working for both upload locations.

**Comment by garrettmflynn** [comment]
Also updated the `staging` specification so that it's a selector with no default value, where you can choose the Main Archive or the Development Server.

**Comment by CodyCBakerPhD** [comment]
Working now!

Oh wow, the popup feels super nice and interactive. Lovely interface for specifying all the information

One minor thing I just noticed - after completing an upload the standalone page resets to this (there was a nice popup about the upload results, though possibly the paths that were successfully uploaded didn't populate)

image

I guess the only thing that looks off about it is the error message 'Filesystem Paths ...' since most users won't know what that is... Is it possible to change that to something like 'Please select files or folders to upload'?

**Comment by CodyCBakerPhD** [comment]
Uhh well this is interesting. I closed the app and restarted to see what the default upload standalone page looks like and now I get this in console

```
(node:3064) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
(Use `electron --trace-deprecation ...` to show where the warning was created)
[5744:1130/123830.054:ERROR:cert_issuer_source_aia.cc(36)] Error parsing cert retrieved from AIA (as DER):
ERROR: Couldn't read tbsCertificate as SEQUENCE
ERROR: Failed parsing Certificate

[5744:1130/123830.641:ERROR:cert_issuer_source_aia.cc(36)] Error parsing cert retrieved from AIA (as DER):
ERROR: Couldn't read tbsCertificate as SEQUENCE
ERROR: Failed parsing Certificate
```

and can't access the standalone page at all anymore

image

**Comment by CodyCBakerPhD** [comment]
Specific error on standalone page

```javascript
Uncaught (in promise) ReferenceError: statusBar is not defined
    at pythonServerClosed (index.ts:63:3)
    at EventEmitter.pythonServerOpened (index.ts:55:15)
```

**Comment by garrettmflynn** [comment]
Hmm I fixed the frontend issue. I can work on the deprecated `crypto` method, that's how we're obscuring the user's API keys in the GUIDE's global JSON configuration.

**Comment by garrettmflynn** [comment]
@CodyCBakerPhD If I create a Dandiset using the Python CLI, how would I define my NIH Award Number?

**Comment by CodyCBakerPhD** [comment]
> @CodyCBakerPhD If I create a Dandiset using the Python CLI, how would I define my NIH Award Number?

By including this section of metadata structure, which appears to autopopulate when doing this using the web API (just tested on staging)

```
{
    ....
    "contributor": {
        "name": "National Institutes of Health (NIH)",
        "roleName": [
            "dcite:Funder"
        ],
        "schemaKey": "Organization",
        "awardNumber": "5 R01 NS 119519-03"
    },
    ....
}
```

**Comment by garrettmflynn** [comment]
While the DANDI-side issues when crating embargoed Dandisets appear to have been fixed, I'm getting 401 (Unauthorized) errors when trying to pull information from these Dandisets using my JavaScript API—including when grabbing their information after creation (see https://github.com/NeurodataWithoutBorders/nwb-guide/issues/534). While they _can_ be created, I can't get their IDs afterwards and therefore cannot upload tothem.

Since embargoing is still commented out, we could move forward with this PR as-is and handle embargoed Dandisets in a follow-up. @CodyCBakerPhD What do you think?

**Comment by CodyCBakerPhD** [comment]
Should the loose selector still be in this PR? Nothing pops up on that bar of my standalone dandi upload page when I go to search/type anything

**Comment by garrettmflynn** [comment]
It should—and will wait until all Dandisets associated to you are loaded / errored before rendering. 

Are there any errors in the console? And your API keys are up to date?

**Comment by CodyCBakerPhD** [comment]
> Are there any errors in the console?

None 🤔

> And your API keys are up to date?

Yep, though only the main one. Didn't add the staging one, are both required for this feature?

**Comment by garrettmflynn** [comment]
They should be independent, though I'll confirm on my end.

**Comment by garrettmflynn** [comment]
I was able to only specify a valid Main API key and have the loose selector work. Can you try replacing your current value with a new one? This may have been lost after #532

**Comment by CodyCBakerPhD** [comment]
> Can you try replacing your current value with a new one?

That is what I did; perhaps we just need to do this one on one

BTW are you testing this on windows?

**Comment by garrettmflynn** [comment]
I have not been. Could have something to do with the OS.

From this, I've also realized that we need to require the users to have at least one API key specified before interacting with either the standalone Uploads page or the Guided Upload page. I'll implement a pop-up for this ASAP.

**Comment by garrettmflynn** [comment]
@CodyCBakerPhD I've added the required changes to block interactions until at least one API key is specified.

Let me know when you'd want to sit down and debug on your system

**Comment by garrettmflynn** [comment]
Additionally, I've opened #537 which may have been the root of your API key issue

**Comment by garrettmflynn** [comment]
Fixed #534. Turns out I wasn't passing the authorization token for metadata request—as well as wasn't handing the pagination of the My Dandisets result.

**Comment by CodyCBakerPhD** [comment]
Selector is working again: it seemed to work fine but console did throw this error after displaying the results window

```javascript
Uncaught (in promise) TypeError: Cannot set properties of null (setting 'innerHTML')
    at DandiResults.updated (DandiResults.js:54:33)
```

**Comment by CodyCBakerPhD** [comment]
The main result of which seems to be this appearance on the page after upload

image

**Comment by CodyCBakerPhD** [comment]
Ah... And this is persistent if I close and restart the app

**Comment by CodyCBakerPhD** [comment]
Since this PR requires this work to debug, I'll also throw in another request

Would it be hard to order entries in the selector with draft versions starting from the top instead of the bottom? Those are the more likely targets for uploads, though uploading to an already published one is not impossible or unusual

**Comment by garrettmflynn** [comment]
Is there an error when the loading is happening? The first error shouldn't change anything related to fetching all of your Dandisets—which is what is happening on the Uploads page on refresh.

**Comment by CodyCBakerPhD** [comment]
Did a hard restart of the console / gave more time after last shut down and that seemed to reset the page

Only thing I notice otherwise is the thing on the conda console (not the app dev console)

```
[13224:1213/104532.219:ERROR:cert_issuer_source_aia.cc(36)] Error parsing cert retrieved from AIA (as DER):
ERROR: Couldn't read tbsCertificate as SEQUENCE
ERROR: Failed parsing Certificate
```

**Comment by CodyCBakerPhD** [comment]
But oddly, the form contents didn't get stuck this time, still see previous error on dev console though

**Comment by CodyCBakerPhD** [comment]
The issue is sporadic for me and seems to affect other things on the app

I just let it close down and waited for about a minute (it also tends to get stuck on the 'killing all active processes bit' then got

image

**Comment by garrettmflynn** [comment]
Hmmm that's weird. I don't have it on my system—and since it's a certificate issue, I think it'll be mostly an issue on your system. I'll try on my Windows PC to see if it pops up there.

Otherwise the ordering and HTML-related error have been fixed.

**Comment by garrettmflynn** [comment]
Can you see if it's fixed by running `main`?

**Comment by CodyCBakerPhD** [comment]
OK, pretty weird issue, present on `main` as well

After a successful upload to dandi using the app, I close down the app and then reboot it

After reboot, it never connects to the backend, and the uploads page says it's waiting to connect to the Flask server (different display message on main, but I assume same cause)

No errors on any console

Attempting to exit the app at this point closes the main window but gets stuck on the 'Killing all previous processes' in the main console

**Comment by CodyCBakerPhD** [comment]
This is on a completely fresh environment following a hard reboot to clear some process that was preventing removal of the SLL .dll files in the conda environment

**Comment by CodyCBakerPhD** [comment]
After like 5 minutes of waiting, this did just randomly pop up in the dev console

```javascript
index.ts:63 Uncaught (in promise) ReferenceError: statusBar is not defined
    at pythonServerClosed (index.ts:63:3)
    at EventEmitter.pythonServerOpened (index.ts:55:15)
```

**Comment by CodyCBakerPhD** [comment]
And at the same time as that, the backend printed the usual 

```
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:4242
```

but still claims to not be connected to the backend - but the app can now successfully close down as usual

**Comment by garrettmflynn** [comment]
We caught the `statusBar` when I initially started working in the Dandiset creation PR. I'll push a quick fix to main for that

**Comment by garrettmflynn** [comment]
Ah sure. The form waits for two conditions: 
1. CPU information is resolved
2. All dandisets are resolved

So if the server is down, it wouldn't load.

**Comment by CodyCBakerPhD** [comment]
OK - considering the issues found here as separate in #540 

The actual features of this PR feel great at this point

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by CodyCBakerPhD** [comment]
One question on that last chromatic page - is it possible to get a story for the new layout? @garrettmflynn

**Pull request merged**
