### PR TITLE
Fix Exit Button

### LINKED ISSUE #327: [Bug] Exit button broken
Hitting the exit button (bottom-right)

image

does not return me to the main page anymore

Seems to have this behavior on each page

### PR DESCRIPTION
**Pull request by garrettmflynn**
fix #327

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
Any easy way to add tests for this one to avoid it occurring again the future?

**Comment by garrettmflynn** [comment]
Done. The function to be tested was in a file that imported a dependency that was too complicated for the testing suite—so I had to move a bunch of stuff around.

**Comment by CodyCBakerPhD** [comment]
Seems the act of changing things around may have impeded some other functionality

When I try to navigate to a pipline on this branch there's a spiny wheel (didn't know that was ever there)

image

```javascript
Uncaught (in promise) ReferenceError: updateURLParams is not defined
    at GuidedHomePage.resume (index.js:96:5)
    at GuidedHomePage.resume (GuidedHome.js:147:25)
    at card.resume (GuidedHome.js:55:45)
    at ProgressCard.<anonymous> (ProgressCard.js:118:58)
    at EventPart.handleEvent (lit-html.ts:2003:29)
```

**Comment by garrettmflynn** [comment]
You're right, good catch. Fixed this import error.

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
