### PR TITLE
Updates to SODA text for the first few pages

### PR DESCRIPTION
**Pull request by garrettmflynn**
This PR brings updates to the HTML from #10 to their own branch for review.

### CODE REVIEW

**Comment by garrettmflynn** [comment]
Can do. 

If this is the expectation, I can keep frontend PRs limited to changes to a single page or, in the case of components, to a canonical page or two. I'd also be happy to split this into several PRs as well if that's desired—though it was organized this way because these are all relatively consistent changes to the SODA language restricted to HTML pages. Most of this will be rewritten as components anyways and, therefore, will go through further review.

Here are the before-and-after shots for this PR:

| File  | Before | After |
| ------------- | ------------- | ------------- |
| splash-screen.html  | 
splash-before
 | No Change (units technically required for CSS)  |
| assets/css/help.html  | Hidden  | Hidden  |
| sections/contact-us/contact_us.html  | Hidden  | Hidden  |
| sections/documentation/documentation.html | Hidden  | Hidden  |
| sections/getting_started/getting_started.html  | getting-started-before  | getting-started-after |
| sections/guided_mode/guided_curate_dataset.html (page 1)  | curate-p1-before | curate-p1-after |
| sections/guided_mode/guided_curate_dataset.html (page 2)  | curate-p2-before | curate-p2-after  |
| sections/guided_mode/guided_curate_dataset.html (page 3)  | curate-p3-before | curate-p3-after |

If we want to discuss / remove changes / resurrect the hidden sections, I'm also happy to talk about that. Previous PRs were just limiting the scope of our concern and I wanted to consistently change HTML entries from SODA to NWB GUIDE, even if not visible.

**Comment by CodyCBakerPhD** [comment]
> can you please paste screenshot(s) for all PRs that involve changes to the front end?

There has to be a better way to do this for the GUIDE project given how many pages are going to be affected over time. Otherwise we'll be up to our necks in one-time screenshots with each review

I think it might be worth trying to figure out how to use Chromatic early on here - it can be setup with a preview workflow that allows us to visualize the changes to each page from a specific PR

**Comment by garrettmflynn** [comment]
I agree with Cody here. This is fine for now—but will quickly get out of hand.

However, using Chromatic will require converting everything we'd like to review into Web Components and adding to Storybook. This would be doable given the workflows outlined in #17 and #18, I'd just need confirmation this is the direction we'd like to go and those PRs merged.

**Comment by bendichter** [comment]
I think if the PR requires more than a few screenshots it's too big

**Comment by garrettmflynn** [comment]
The inclusion of Chromatic is someone independent of the small frontend PR problem—as even small changes to one component could affect each usage in a different way depending on their container. 

Of course, changes to multiple files are more likely to have more changes across more pages, while changes to a small set of files likely have fewer changes to fewer pages. But that's a major generalization, especially when using Web Components

Chromatic basically automates the screenshot process and ensures a comprehensive view of the changes. If we want these benefits, then I'd think we'd want to include it in our workflow. On the other hand, if we're fine with manual screenshots of canonical usages (as evidenced by the previous table), then we don't need it.

**Comment by CodyCBakerPhD** [comment]
> as even small changes to one component could affect each usage in a different way depending on their container.

This is the big one that I foresee, see the [demo video from the Chromatic team](https://www.youtube.com/watch?v=9o6uB1X-LZ8&embeds_euri=https%3A%2F%2Fwww.chromatic.com%2F&source_ve_path=MjM4NTE&feature=emb_title&ab_channel=Chromatic) Garrett posted earlier to see how easy it makes it to spot before nad after differences from automated screenshots

**Comment by CodyCBakerPhD** [comment]
> This would be doable given the workflows outlined in https://github.com/catalystneuro/nwb-guide/pull/17 and https://github.com/catalystneuro/nwb-guide/pull/18, I'd just need confirmation this is the direction we'd like to go and those PRs merged.

You wanted to do those anyway for more efficient refactoring, right?

**Comment by garrettmflynn** [comment]
Yes, I just meant to indicate that using Chromatic in a useful way is
dependent on those PRs. So we couldn’t use it immediately on the above
changes.

**Comment by CodyCBakerPhD** [comment]
> My current plan is to make Web Components based on the original pages and submit separate PRs for each of them. These can be reviewed either with Chromatic 

Perfect, that should be best for long-term scalability

**Pull request closed without merging**
