### PR TITLE
Fix custom schema validation

### LINKED ISSUE #634: species constraints inconsistent
### Describe the issue

image

The form allows me to enter any species that follows the structure of a binomial Latin name. However, proceeding requires that the name is on a list of approved names.

I would like to be able to proceed even with a species name that is not on this list. I know  "Monkey monkey" is not a valid name, but I don't want the GUIDE to prohibit the creation of NWB files from new species

### Steps to Reproduce

See above

### Operating System

OSX

### GUIDE Version

main branch

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

### PR DESCRIPTION
**Pull request by garrettmflynn**
fix #634 

There's some custom schema validation logic that wasn't referring to the correct schema. Fixed!

### CODE REVIEW

**Comment by garrettmflynn** [comment]
Can you try again? This is working fine on my end.

Avoided a stray error in the Search component with the last push. May have something to do with what you observed

**Comment by CodyCBakerPhD** [comment]
> Can you try again? This is working fine on my end.

I'm surprised; after digging into this it was coming from the neuroconv metadata schema validation

I opened https://github.com/catalystneuro/neuroconv/pull/769, which fixed it for me when using this branch

I know we've had issues/differences with the jsonschema python library on Mac - maybe mine is a Windows specific issue?

**Comment by garrettmflynn** [comment]
Huh weird. Since this is the pattern used to check the validity of the value, we shouldn't receive any errors regarding the `enum` field, though, right?

**Comment by CodyCBakerPhD** [comment]
> we shouldn't receive any errors regarding the enum field, though, right?

I might not have read the error from the popup window closely enough; only digging through the traceback led me to the source and the right message

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by CodyCBakerPhD** [comment]
This works for me now

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by CodyCBakerPhD** [comment]
Also, any way to write a test for this?

**Comment by garrettmflynn** [comment]
This one is much more straightforward than the others. I'll start with this next week.

**Comment by CodyCBakerPhD** [comment]
Pydantic v2 issues causing CI failure should be fixed with the pin to pyinstaller hook contrib + https://github.com/catalystneuro/neuroconv/pull/770

Ref; https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/610

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
