### PR TITLE
Allow specifying subject and session IDs for single-session case

### LINKED ISSUE #689: Unable to define subject_id and session_id in single-session mode
### Describe the issue

I have no way of indicating the session_id or subject_id in the single-session mode. The GUIDE just assumes that it is Subject 001 and Session 1 even though I don't specify that anywhere.

### Steps to Reproduce

n.a.

### Operating System

osx

### GUIDE Version

main branch

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

### PR DESCRIPTION
**Pull request by garrettmflynn**
fix #689

### CODE REVIEW

**Comment by bendichter** [comment]
image

The error messages are showing up twice for me on page load. I would really rather they don't show up at all until I hit submit.

**Comment by bendichter** [comment]
I also get taken to this page, which should not be reachable in single-session mode

image

**Comment by garrettmflynn** [comment]
Alright this should be good to review now

**Comment by bendichter** [comment]
image

Now for some reason it is not letting me specify Age instead of DOB

**Comment by garrettmflynn** [comment]
Good catch, thanks! DOB and Age use an alternative mechanism to handle requirement status (i.e. conditional requirements), so these properties had to be excluded from the recent changes.

**Comment by garrettmflynn** [comment]
@bendichter This should be good to go!

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn Failings tests for this PR

**Comment by garrettmflynn** [comment]
Thanks for the ping. Fixed

**Comment by bendichter** [comment]
LGTM!

**Review by bendichter — APPROVED** [review]

**Pull request merged**
