### PR TITLE
[WIP] Add code coverage testing of app and server

### LINKED ISSUE #111: Add codecov
We do have some minimal back-end tests up and running but would be good to track coverage of lines from apiNeuroConv and managerNeuroConv

@rly could you help set this up like you have it on PyNWB?

### PR DESCRIPTION
**Pull request by rly**
Fix #111.

### CODE REVIEW

**Comment by rly** [comment]
Coverage for this branch: https://app.codecov.io/gh/NeurodataWithoutBorders/nwb-guide/tree/add_coverage/

**Comment by CodyCBakerPhD** [comment]
So based on the report and details in the changelog about vitetest, this also effectively counts coverage of front-end components via vitetest? That's cool

I'm assuming the package lock changes are necessary to use coverage versions of vitetest and others reasons? I defer to @garrettmflynn on if the changes to the package lock are OK but the app seems to work fine for me atm

**Comment by rly** [comment]
> So based on the report and details in the changelog about vitetest, this also effectively counts coverage of front-end components via vitetest? That's cool

Yep!
 
> I'm assuming the package lock changes are necessary to use coverage versions of vitetest and others reasons? I defer to @garrettmflynn on if the changes to the package lock are OK but the app seems to work fine for me atm

Yes, I needed to install "@vitest/coverage-v8" as a dev dependency. That also meant updating "vitest". Together, that resulted in a few needed changes to package-lock.json

**Review by garrettmflynn — APPROVED** [review]
Looks fine to me! As long as it builds, it should be good.

**Pull request merged**
