### PR TITLE
Fix emoji rendering

### PR DESCRIPTION
**Pull request by garrettmflynn**
This PR breaks out the font-family to use with emojis so we can consistently apply this across different Web Components without changing the global font style.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
Hmmm... that's not good =\

When I get to the subject table for this PR nothing renders and in the dev console I get

```javascript
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at ProgressCard.render (ProgressCard.js:42:51)
    at ProgressCard.update (lit-element.ts:160:24)
    at ProgressCard.performUpdate (reactive-element.ts:1331:14)
    at ProgressCard.scheduleUpdate (reactive-element.ts:1263:17)
    at ProgressCard.__enqueueUpdate (reactive-element.ts:1235:25)
3Table.js:47 Uncaught (in promise) ReferenceError: emojiFontFamily is not defined
    at new Table (Table.js:47:24)
    at GuidedSubjectsPage.render (GuidedSubjects.js:80:22)
    at GuidedSubjectsPage.update (lit-element.ts:160:24)
    at GuidedSubjectsPage.performUpdate (reactive-element.ts:1331:14)
    at GuidedSubjectsPage.scheduleUpdate (reactive-element.ts:1263:17)
    at GuidedSubjectsPage.__enqueueUpdate (reactive-element.ts:1235:25)
3ProgressCard.js:42 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at ProgressCard.render (ProgressCard.js:42:51)
    at ProgressCard.update (lit-element.ts:160:24)
    at ProgressCard.performUpdate (reactive-element.ts:1331:14)
    at ProgressCard.scheduleUpdate (reactive-element.ts:1263:17)
    at ProgressCard.__enqueueUpdate (reactive-element.ts:1235:25)
2Table.js:47 Uncaught (in promise) ReferenceError: emojiFontFamily is not defined
    at new Table (Table.js:47:24)
    at GuidedSubjectsPage.render (GuidedSubjects.js:80:22)
    at GuidedSubjectsPage.update (lit-element.ts:160:24)
    at GuidedSubjectsPage.performUpdate (reactive-element.ts:1331:14)
    at GuidedSubjectsPage.scheduleUpdate (reactive-element.ts:1263:17)
    at GuidedSubjectsPage.__enqueueUpdate (reactive-element.ts:1235:25)
```

**Comment by CodyCBakerPhD** [comment]
But, for whatever reason, when I try it on `main` now the info icons render they way they ought to

Quite strange...

**Comment by garrettmflynn** [comment]
One of the merges must have removed the link to the emojiFontFamily variable. Just added back now, let me know if it works

**Comment by CodyCBakerPhD** [comment]
OK yeah that did it. Working fine now, thanks!

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
