### PR TITLE
Create loose selector (autocomplete) for JSONSchemaForm

### PR DESCRIPTION
**Pull request by garrettmflynn**
A component of #512 to allow for cross-row comparison. Also makes the Species interactions uniform across tables and forms.

### CODE REVIEW

**Comment by garrettmflynn** [comment]
@CodyCBakerPhD This is ready to go—aside from any fixes we want on the DANDI side. I added the common names as additional "keywords", so those are still searchable and show up in the form autocomplete view.

**Comment by CodyCBakerPhD** [comment]
Bug: session start time is now exposed at global NWB file metadata

image

Same for Subject ID

image

**Comment by CodyCBakerPhD** [comment]
And subject age/dob/etc

**Comment by CodyCBakerPhD** [comment]
Easiest fix might just be to do what we were going to do anyway and remove those pages at the start and go straight to selecting data formats

**Comment by garrettmflynn** [comment]
Yep agreed

**Comment by garrettmflynn** [comment]
Fixed removing the instance-specific properties in the metadata preprocessing script here. Will remove the global pages in a separate PR

**Comment by CodyCBakerPhD** [comment]
> Fixed removing the session-specific properties in the metadata preprocessing script here. Will remove the global pages in a separate PR

I still see all the same ones after deleting and regenerating the pipeline - did I need to do a rebuild with `npm ci` as well?

**Comment by garrettmflynn** [comment]
Argh. My bad, flipped the default value for one of the arguments that is used to determine whether to generate the global vs. session metadata. 

Just fixed and tested locally.

**Comment by CodyCBakerPhD** [comment]
I can confirm the unintended fields are removed from the global forms, but now the auto-complete is no longer working on that page or the subject metadata table page (the dropdown)

**Comment by garrettmflynn** [comment]
Hmm I just tested and it works fine for me. Do you see any errors in the console?

Just as a reminder, it doesn't populate immediately because of the required API call—so it won't show up as a search component when you reload. Though if you navigate off and back on, it should.

**Comment by CodyCBakerPhD** [comment]
The only 4 things that pop up in the console (conda or in-app dev) when I type stuff in the subject species box are

```
127.0.0.1 - - [21/Nov/2023 19:20:48] "OPTIONS /neuroconv/validate HTTP/1.1" 200 -

127.0.0.1 - - [21/Nov/2023 19:20:48] "OPTIONS /neuroconv/validate HTTP/1.1" 200 -

127.0.0.1 - - [21/Nov/2023 19:20:48] "POST /neuroconv/validate HTTP/1.1" 200 -

127.0.0.1 - - [21/Nov/2023 19:20:48] "POST /neuroconv/validate HTTP/1.1" 200 -
```

No matter how long I wait

Then, when I first navigate to the subject metadata table page, closest thing I see to an error is

```javascript
Uncaught (in promise) undefined :5173/?page=conversi…IDE+Tutorial+Data:1
<html>
<body>
<!--StartFragment-->
Promise.then (async) |   |  
-- | -- | --
  | (anonymous) | @ | globals.ts:15
  | resolve | @ | globals.ts:14
  | preprocessMetadataSchema | @ | base-metadata.schema.ts:67
  | default | @ | subject.schema.ts:11
  | render | @ | GuidedSubjects.js:115
  | update | @ | lit-element.ts:160
  | performUpdate | @ | reactive-element.ts:1329
  | scheduleUpdate | @ | reactive-element.ts:1261
  | __enqueueUpdate | @ | reactive-element.ts:1233
  | await in __enqueueUpdate (async) |   |  
  | requestUpdate | @ | reactive-element.ts:1208
  | (anonymous) | @ | Dashboard.js:214
  | Promise.then (async) |   |  
  | setMain | @ | Dashboard.js:213
  | Dashboard.window.onpushstate.window.onpopstate | @ | Dashboard.js:129
  | Dashboard.window.history.pushState | @ | Dashboard.js:118
  | #activatePage | @ | Dashboard.js:309
  | attributeChangedCallback | @ | Dashboard.js:159
  | main.onTransition | @ | Dashboard.js:278
  | to | @ | Page.js:85
  | onNext | @ | GuidedPathExpansion.js:226
  | await in onNext (async) |   |  
  | handleEvent | @ | lit-html.ts:2018

<!--EndFragment-->
</body>
</html>
```

**Comment by garrettmflynn** [comment]
Whoa. Can you regenerate Tutorial pipeline and see if it persists?

**Comment by CodyCBakerPhD** [comment]
> Whoa. Can you regenerate the Tutorial pipeline and see if it persists?

That's what I have been doing - including re-running `npm ci`

Only thing I haven't done is a complete reinstall of environment but I can try that next

**Comment by CodyCBakerPhD** [comment]
OK a fresh environment fixed everything 🤷‍♀️

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by CodyCBakerPhD** [comment]
Chromatic failing on this PR however: https://github.com/NeurodataWithoutBorders/nwb-guide/actions/runs/6951875051/job/18914569311

**Pull request merged**
