### PR TITLE
Preload imports on Flask server

### LINKED ISSUE #340: Preload imports on startup from safe endpoint
@garrettmflynn Can you point me to the relevant code on the front-end that launches the first call to the Flask endpoint? (I think it used to have something about 'echo'? Or maybe it's the thing that checks if the backend is connected and running?)

I'd like to add a simple endpoint to trigger various imports just after launch (but as separate hidden operation) to reduce the instantaneous speed of the now locally scoped operations

### PR DESCRIPTION
**Pull request by CodyCBakerPhD**
fix #340 

Current draft for how I imagine this would go - trying to think of a way to test it, but IDK if it's really possible aside from noticing that the 'loading interfaces' page should now be instantaneous

@garrettmflynn This would also trigger on hot reload right?

### CODE REVIEW

**Comment by garrettmflynn** [comment]
Looks good. You're correct, this would trigger on hot reload.

I think your "test" is on the mark. Failure is easy to see too—but success requires a bit more. You _could_ send something back to the frontend from the import and check for that

**Comment by CodyCBakerPhD** [comment]
> You could send something back to the frontend from the import and check for that

I technically return `True` from the endpoint success, would that be something you could develop a test for? Or would you prefer a better error/success code (like an integer)

**Comment by garrettmflynn** [comment]
`True` is fine. Then the enpoint will either return that or an inbuilt error. 

Though what is the condition(s) you're actually interested in testing for? Whether the import itself errors?

**Comment by CodyCBakerPhD** [comment]
> Though what is the condition(s) you're actually interested in testing for? Whether the import itself errors?

Yeah, that's as close as we can get. If that sends back `True` it means its cached in memory on the Flask server, so the speed benefit _should_ work indirectly as a consequence

**Comment by garrettmflynn** [comment]
Awesome. If you want to actually write a Python test, you can follow the format noted here: 

https://github.com/NeurodataWithoutBorders/nwb-guide/blob/c5e778ab7cf05f18df3115853aab5c2e86a3273f/pyflask/tests/test_neuroconv.py#L7

You don't need the validate() call since it is sufficient that the endpoint doesn't error

**Comment by garrettmflynn** [comment]
Oh sure. You can check if True is returned from the request—though that would be it

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn Backend status symbol on the app is yellow and dev console outputs

```javascript
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at GuidedStructurePage.updated (GuidedStructure.js:80:20)
    at GuidedStructurePage._$didUpdate (reactive-element.ts:1380:10)
    at GuidedStructurePage.performUpdate (reactive-element.ts:1345:12)
    at GuidedStructurePage.scheduleUpdate (reactive-element.ts:1263:17)
    at GuidedStructurePage.__enqueueUpdate (reactive-element.ts:1235:25)
```

Ideas how to fix?

**Comment by garrettmflynn** [comment]
Hmmm how are you getting this? Just ran through with the Tutorial pipeline from scratch and didn't see this.

**Comment by CodyCBakerPhD** [comment]
My workflow

-> `git checkout preload_imports`
-> `git pull`
-> `npm start`
-> backend status light is yellow
-> dev console says API commands were sent to endpoint and look fine
-> navigate any pipeline from scratch up to interface page
-> no interfaces, dev console spits out the above error

Actually, I just checked and I'm seeing this on `main` now as well, perhaps an issue with a recent merge? And one that's Windows specific?

**Comment by garrettmflynn** [comment]
Do you notice anything odd going on with the backend in the main console? 

Otherwise I'll try to see if I can trigger this myself tomorrow.

**Comment by CodyCBakerPhD** [comment]
The only thing in the command prompt out of the ordinary is

```
Skip checkForUpdatesAndNotify because application is not packed
```

no other activity as I go through the first few pages of a pipeline

**Comment by garrettmflynn** [comment]
Alright fixed. There were actually two separate issues here:

1) You were returning after calling `preloadFlaskImports`, interrupting the status update that indicates a successful backend connection.

2) Not having interfaces defined on the global object would result in the error you saw in `GuidedStructure`. I've made sure this is filled in if undefined

**Comment by CodyCBakerPhD** [comment]
Ohhh: https://github.com/NeurodataWithoutBorders/nwb-guide/pull/342/commits/e1f13248d790b8cfef0825e3eb7d74adb944a042#diff-28a5296a524fc5a6da149c021fb048736dd8586329a8d9095bb79c4c78d4f011R112

I see, thanks for debugging my JavaScript!

**Comment by CodyCBakerPhD** [comment]
OK, can you give this a try when you review? Works well on my end

The connect to the backend now takes just a slight moment to go from yellow to green (the time it would have taken on the first screen running a backend operation) and as such if you, for example, navigate to the interfaces screen of a fresh pipeline, it is now instantaneous

**Review by garrettmflynn — APPROVED** [review]
Yep, looks good!

**Pull request merged**
