### PR TITLE
Final Mac Workflow Updates

### PR DESCRIPTION
**Pull request by garrettmflynn**
This PR is intended to get the CI Mac distribution to work on non-M1 Macs.

### CODE REVIEW

**Comment by garrettmflynn** [comment]
As it stands, this PR has implemented improved error checking by passing all console outputs to the browser for review. 

The first problem addressed was the inability to resolve `ndx_dandi_icephys/spec/ndx-dandi-icephys.namespace.yaml`, which was achieved by adding another flag to the PyInstaller build.

One outstanding problem still remains: It seems that the DANDI API's multiprocessing is being blocked, even when `multiprocessing.freeze_support()` is removed. As such, it seems like this may be a separate problem. 

The error received in both cases is: 
```
Request to upload failed: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {EXIT(1)}
```

@CodyCBakerPhD Do you have any ideas why the same error would be thrown. The current version of this PR **still has** the `freeze_support` call and, if removed, we'll want to monitor the created processes closely (as explained in #303).

**Comment by CodyCBakerPhD** [comment]
Can confirm, the 0.0.3 release of the `.dmg`, which was made using this branch, actually works just fine on M1 too, just not including the DANDI upload step which gives this similar stack trace

Cheers 🎉

<details> <summary>Traceback for Failed Upload</summary>

[main-process]: [Parallel(n_jobs=-1)]: Using backend LokyBackend with 10 concurrent workers.

(anonymous) @ index-4a657edf.js:48400
emit @ node:events:526
onMessage @ node:electron/js2c/renderer_init:69
index-4a657edf.js:48400 [main-process]: Source data is valid!
Source data is valid!
Source data is valid!
Source data is valid!
Source data is valid!
Metadata is valid!
conversion_options is valid!
NWB file saved at /Users/codybaker/NWB_GUIDE/stubs/NWB GUIDE Tutorial Data/sub-mouse2/sub-mouse2_ses-070623.nwb!
Source data is valid!
Metadata is valid!
conversion_options is valid!
NWB file saved at /Users/codybaker/NWB_GUIDE/conversions/NWB GUIDE Tutorial Data/sub-mouse2/sub-mouse2_ses-070623.nwb!
Source data is valid!
Metadata is valid!
conversion_options is valid!
NWB file saved at /Users/codybaker/NWB_GUIDE/conversions/NWB GUIDE Tutorial Data/sub-mouse2/sub-mouse2_ses-060623.nwb!
Source data is valid!
Metadata is valid!
conversion_options is valid!
NWB file saved at /Users/codybaker/NWB_GUIDE/conversions/NWB GUIDE Tutorial Data/sub-mouse1/sub-mouse1_ses-060623.nwb!
Source data is valid!
Metadata is valid!
conversion_options is valid!
NWB file saved at /Users/codybaker/NWB_GUIDE/conversions/NWB GUIDE Tutorial Data/sub-mouse1/sub-mouse1_ses-070623.nwb!
PATH                 SIZE DONE    DONE% CHECKSUM STATUS MESSAGE   
200560/dandiset.yaml                             done   updated   
Summary:                  0 Bytes                1 done 1 updated 
                          <0.00%                                  

index-4a657edf.js:48400 [main-process]: Traceback (most recent call last):
  File "app.py", line 85, in <module>
Exception: No port provided for the NWB GUIDE backend.
[81958] Failed to execute script 'app' due to unhandled exception!

(anonymous) @ index-4a657edf.js:48400
emit @ node:events:526
onMessage @ node:electron/js2c/renderer_init:69
index-4a657edf.js:48400 [main-process]: [2023-08-18 22:29:24,404] INFO in app: Starting server on port 35

(anonymous) @ index-4a657edf.js:48400
emit @ node:events:526
onMessage @ node:electron/js2c/renderer_init:69
index-4a657edf.js:48400 [main-process]: [2023-08-18 22:29:24,405] INFO in app: Starting server on port 31

(anonymous) @ index-4a657edf.js:48400
emit @ node:events:526
onMessage @ node:electron/js2c/renderer_init:69
2index-4a657edf.js:48400 [main-process]:  * Serving Flask app 'app'
 * Debug mode: off

index-4a657edf.js:48400 [main-process]: [2023-08-18 22:29:24,410] INFO in app: Starting server on port 33

(anonymous) @ index-4a657edf.js:48400
emit @ node:events:526
onMessage @ node:electron/js2c/renderer_init:69
index-4a657edf.js:48400 [main-process]:  * Serving Flask app 'app'
 * Debug mode: off

3index-4a657edf.js:48400 [main-process]: Permission denied

(anonymous) @ index-4a657edf.js:48400
emit @ node:events:526
onMessage @ node:electron/js2c/renderer_init:69
index-4a657edf.js:48400 [main-process]: [2023-08-18 22:29:24,472] INFO in app: Starting server on port 37

(anonymous) @ index-4a657edf.js:48400
emit @ node:events:526
onMessage @ node:electron/js2c/renderer_init:69
index-4a657edf.js:48400 [main-process]:  * Serving Flask app 'app'
 * Debug mode: off

index-4a657edf.js:48400 [main-process]: [2023-08-18 22:29:24,473] INFO in app: Starting server on port 41

(anonymous) @ index-4a657edf.js:48400
emit @ node:events:526
onMessage @ node:electron/js2c/renderer_init:69
index-4a657edf.js:48400 [main-process]:  * Serving Flask app 'app'
 * Debug mode: off

index-4a657edf.js:48400 [main-process]: Permission denied

(anonymous) @ index-4a657edf.js:48400
emit @ node:events:526
onMessage @ node:electron/js2c/renderer_init:69
index-4a657edf.js:48400 [main-process]: [2023-08-18 22:29:24,486] INFO in app: Starting server on port 49

(anonymous) @ index-4a657edf.js:48400
emit @ node:events:526
onMessage @ node:electron/js2c/renderer_init:69
index-4a657edf.js:48400 [main-process]:  * Serving Flask app 'app'
 * Debug mode: off

index-4a657edf.js:48400 [main-process]: Permission denied

(anonymous) @ index-4a657edf.js:48400
emit @ node:events:526
onMessage @ node:electron/js2c/renderer_init:69
index-4a657edf.js:48400 [main-process]: [2023-08-18 22:29:24,490] INFO in app: Starting server on port 39

(anonymous) @ index-4a657edf.js:48400
emit @ node:events:526
onMessage @ node:electron/js2c/renderer_init:69
index-4a657edf.js:48400 [main-process]:  * Serving Flask app 'app'
 * Debug mode: off

index-4a657edf.js:48400 [main-process]: Permission denied

(anonymous) @ index-4a657edf.js:48400
emit @ node:events:526
onMessage @ node:electron/js2c/renderer_init:69
index-4a657edf.js:48400 [main-process]: joblib/externals/loky/backend/resource_tracker.py:113: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some folders/sempahores might leak.

(anonymous) @ index-4a657edf.js:48400
emit @ node:events:526
onMessage @ node:electron/js2c/renderer_init:69
index-4a657edf.js:48400 [main-process]: [2023-08-18 22:29:24,506] INFO in app: Starting server on port 45

(anonymous) @ index-4a657edf.js:48400
emit @ node:events:526
onMessage @ node:electron/js2c/renderer_init:69
index-4a657edf.js:48400 [main-process]:  * Serving Flask app 'app'

index-4a657edf.js:48400 [main-process]:  * Debug mode: off

index-4a657edf.js:48400 [main-process]: Permission denied

(anonymous) @ index-4a657edf.js:48400
emit @ node:events:526
onMessage @ node:electron/js2c/renderer_init:69
index-4a657edf.js:48400 [main-process]: [2023-08-18 22:29:24,529] INFO in app: Starting server on port 43

(anonymous) @ index-4a657edf.js:48400
emit @ node:events:526
onMessage @ node:electron/js2c/renderer_init:69
index-4a657edf.js:48400 [main-process]:  * Serving Flask app 'app'
 * Debug mode: off

index-4a657edf.js:48400 [main-process]: Permission denied

(anonymous) @ index-4a657edf.js:48400
emit @ node:events:526
onMessage @ node:electron/js2c/renderer_init:69
index-4a657edf.js:48400 [main-process]: [2023-08-18 22:29:24,585] ERROR in app: Exception on /neuroconv/upload [POST]
Traceback (most recent call last):
  File "apis/neuroconv.py", line 118, in post
  File "manageNeuroconv/manage_neuroconv.py", line 352, in upload_to_dandi
  File "neuroconv/tools/data_transfers.py", line 322, in automatic_dandi_upload
    dandi_organize(paths=str(nwb_folder_path), dandiset_path=str(dandiset_path))
  File "dandi/organize.py", line 820, in organize
  File "joblib/parallel.py", line 1952, in __call__
  File "joblib/parallel.py", line 1595, in _get_outputs
  File "joblib/parallel.py", line 1699, in _retrieve
  File "joblib/parallel.py", line 1734, in _raise_error_fast
  File "joblib/parallel.py", line 736, in get_result
  File "joblib/parallel.py", line 754, in _return_or_raise
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {EXIT(1)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask/app.py", line 1484, in full_dispatch_request
  File "flask/app.py", line 1469, in dispatch_request
  File "flask_restx/api.py", line 404, in wrapper
  File "flask/views.py", line 109, in view
  File "flask_restx/resource.py", line 46, in dispatch_request
  File "apis/neuroconv.py", line 122, in post
  File "flask_restx/namespace.py", line 153, in abort
  File "flask_restx/errors.py", line 28, in abort
  File "flask/helpers.py", line 277, in abort
  File "werkzeug/exceptions.py", line 861, in __call__
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

(anonymous) @ index-4a657edf.js:48400
emit @ node:events:526
onMessage @ node:electron/js2c/renderer_init:69
index-4a657edf.js:48400 [main-process]: 127.0.0.1 - - [18/Aug/2023 22:29:24] "[35m[1mPOST /neuroconv/upload HTTP/1.1[0m" 500 -

(anonymous) @ index-4a657edf.js:48400
emit @ node:events:526
onMessage @ node:electron/js2c/renderer_init:69
index-4a657edf.js:48459          POST http://127.0.0.1:4242/neuroconv/upload 500 (INTERNAL SERVER ERROR)
run$1 @ index-4a657edf.js:48459
onNext @ index-4a657edf.js:169616
await in onNext (async)
handleEvent @ index-4a657edf.js:499
index-4a657edf.js:48467 Uncaught (in promise) Error: Request to upload failed: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {EXIT(1)}
    at run$1 (index-4a657edf.js:48467:11)
    at async GuidedFooter.onNext [as __onNext] (index-4a657edf.js:169616:23)
run$1 @ index-4a657edf.js:48467
await in run$1 (async)
handleEvent @ index-4a657edf.js:499
index-4a657edf.js:48400 [main-process]: Traceback (most recent call last):
  File "app.py", line 85, in <module>
Exception: No port provided for the NWB GUIDE backend.
[81969] Failed to execute script 'app' due to unhandled exception!

(anonymous) @ index-4a657edf.js:48400
emit @ node:events:526
onMessage @ node:electron/js2c/renderer_init:69

</details>

Biggest last remaining issue to tackle with the Mac release is the signing/certification

<details> <summary>App Launch Dev Console </summary>

main-process]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4242
[33mPress CTRL+C to quit[0m

(anonymous) @ index-4a657edf.js:48400
index-4a657edf.js:48400 [main-process]: 127.0.0.1 - - [18/Aug/2023 22:34:04] "GET /startup/echo?arg=server%20ready HTTP/1.1" 200 -

(anonymous) @ index-4a657edf.js:48400
index-4a657edf.js:48400 [main-process]: Error: Error: Cannot find latest-mac.yml in the latest release artifacts (https://github.com/catalystneuro/nwb-guide/releases/download/v0.0.1/latest-mac.yml): HttpError: 404 
"method: GET url: https://github.com/NeurodataWithoutBorders/nwb-guide/releases/download/v0.0.1/latest-mac.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Sat, 19 Aug 2023 02:34:04 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "ED1E:6216:3281AC:4402C9:64E02A1C"
}
    at createHttpError (/Applications/NWB GUIDE.app/Contents/Resources/app.asar/build/main/main.js:4291:12)
    at ElectronHttpExecutor.handleResponse (/Applications/NWB GUIDE.app/Contents/Resources/app.asar/build/main/main.js:4375:16)
    at ClientRequest.<anonymous> (/Applications/NWB GUIDE.app/Contents/Resources/app.asar/build/main/main.js:4346:18)
    at ClientRequest.emit (node:events:526:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:6917)
    at SimpleURLLoaderWrapper.emit (node:events:526:28)
    at Object.newError (/Applications/NWB GUIDE.app/Contents/Resources/app.asar/build/main/main.js:6586:21)
    at GitHubProvider.getLatestVersion (/Applications/NWB GUIDE.app/Contents/Resources/app.asar/build/main/main.js:15224:40)
    at async MacUpdater.getUpdateInfoAndProvider (/Applications/NWB GUIDE.app/Contents/Resources/app.asar/build/main/main.js:15669:15)
    at async MacUpdater.doCheckForUpdates (/Applications/NWB GUIDE.app/Contents/Resources/app.asar/build/main/main.js:15683:22)
(anonymous) @ index-4a657edf.js:48400
index-4a657edf.js:48400 [main-process]: (node:82033) UnhandledPromiseRejectionWarning: Error: Cannot find latest-mac.yml in the latest release artifacts (https://github.com/catalystneuro/nwb-guide/releases/download/v0.0.1/latest-mac.yml): HttpError: 404 
"method: GET url: https://github.com/NeurodataWithoutBorders/nwb-guide/releases/download/v0.0.1/latest-mac.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Sat, 19 Aug 2023 02:34:04 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "ED1E:6216:3281AC:4402C9:64E02A1C"
}
    at createHttpError (/Applications/NWB GUIDE.app/Contents/Resources/app.asar/build/main/main.js:4291:12)
    at ElectronHttpExecutor.handleResponse (/Applications/NWB GUIDE.app/Contents/Resources/app.asar/build/main/main.js:4375:16)
    at ClientRequest.<anonymous> (/Applications/NWB GUIDE.app/Contents/Resources/app.asar/build/main/main.js:4346:18)
    at ClientRequest.emit (node:events:526:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:6917)
    at SimpleURLLoaderWrapper.emit (node:events:526:28)
    at Object.newError (/Applications/NWB GUIDE.app/Contents/Resources/app.asar/build/main/main.js:6586:21)
    at GitHubProvider.getLatestVersion (/Applications/NWB GUIDE.app/Contents/Resources/app.asar/build/main/main.js:15224:40)
    at async MacUpdater.getUpdateInfoAndProvider (/Applications/NWB GUIDE.app/Contents/Resources/app.asar/build/main/main.js:15669:15)
    at async MacUpdater.doCheckForUpdates (/Applications/NWB GUIDE.app/Contents/Resources/app.asar/build/main/main.js:15683:22)
(Use `NWB GUIDE --trace-warnings ...` to show where the warning was created)
(anonymous) @ index-4a657edf.js:48400
index-4a657edf.js:48400 [main-process]: (node:82033) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 203)

</details>

which indicates it may possible simply not be verifiable while the release is in private draft?

**Comment by CodyCBakerPhD** [comment]
Can confirm, once I set the release as public (published - and no cleaning up the .yml files there either since they are used for signing) the warnings went away

Only one left is

```javascript
[main-process]: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:4242
[33mPress CTRL+C to quit[0m
```

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by CodyCBakerPhD** [comment]
However, the previous warning in console about version mismatch did not prevent anything from working

And doing the public release still does not resolve the

```
“NWB GUIDE.app” can’t be opened because Apple cannot check it for malicious software.
```

problem

**Comment by CodyCBakerPhD** [comment]
So for now, Mac users will simply have to go into their security and privacy options and manually allow it to run on their device, similar to Windows users

**Pull request merged**
